// Liftosaur watch workout — model + controller.
//
// The app works STANDALONE in the gym: the plan is baked in at build time
// (source/PlanData.mc, generated by tools/plan_from_liftosaur.py from the user's
// Liftosaur program), so there is no BLE and no network during a workout.
//
// Responsibilities:
//   - hold the workout cursor (day / exercise / set) and what has been logged
//   - persist that cursor so an accidental exit does not lose the session
//   - run the rest countdown between sets (with a vibrate)
//   - record a Garmin activity (strength training) for the session
//
// The BLE streaming experiment (LiftBleTransport / RecordingController /
// SampleBuffer) is deliberately NOT used here: it is parked, see docs/04.

import Toybox.Activity;
import Toybox.ActivityRecording;
import Toybox.Application;
import Toybox.Attention;
import Toybox.FitContributor;
import Toybox.Lang;
import Toybox.Math;
import Toybox.Sensor;
import Toybox.System;
import Toybox.Time;
import Toybox.Timer;
import Toybox.WatchUi;

// Accelerometer magnitude hysteresis band, in milli-G (1000 = 1 G). A rep's
// concentric phase pushes the magnitude well above 1 G; the low threshold
// must clear normal standing/holding noise so it does not double-count.
const ACCEL_HIGH_MILLI_G = 1300;
const ACCEL_LOW_MILLI_G = 1100;

const STORE_KEY = "lift_workout_v1";

class WorkoutController {

    private var _days;          // Array of day dictionaries from LiftPlan
    private var _section;       // "Week 1" — the section the chosen day came from
    private var _dayIndex;      // index into _days
    private var _exIndex;
    private var _setIndex;
    private var _logged;        // Array of Arrays of Booleans
    private var _weights;       // Array of Arrays of Numbers (editable per set)
    private var _reps;          // Array of Arrays of Numbers
    private var _started;       // workout in progress
    private var _session;       // ActivityRecording.Session
    private var _startedAt;     // Time.now().value() when the session began; 0 = unknown
    private var _finalElapsedMs; // elapsedMs() frozen at resolveSave(); -1 = not resolved yet

    private var _restRemaining;
    private var _restTotal;
    private var _restTimer;

    private var _setsDone;
    private var _setsTotal;
    private var _program;
    private var _pendingBody;
    private var _pendingSets;
    private var _comms;                 // set by the app; null in tests
    private var _programs;              // Array of program dicts from the backend
    private var _programIndex;
    private var _programId;
    private var _awaitingReps;          // the AMRAP "how many did you get?" step
    private var _repsEditing;
    private var _activityNote;          // what happened to the Garmin activity
    private var _syncNote;              // what happened to the Liftosaur upload
    private var _lapsAdded;
    private var _sessionStopped;
    private var _info;                  // last fetched exercise history
    private var _historyIndex;          // which "recent" session the history list has open

    // ---- exit after finish (Task 1) ----
    private var _exitPending;      // finish resolved; waiting for the upload (or the watchdog)
    private var _exitTimer;        // one-shot watchdog
    private var _exitRequestedAt;  // seconds, for the minimum on-screen dwell

    // ---- FIT developer fields (Task 2/3/4) ----
    private var _fExercise;   // LAP, STRING  - exercise name
    private var _fSetIndex;   // LAP, UINT8   - 1-based within the exercise
    private var _fWeightLb;   // LAP, UINT16  - lb
    private var _fReps;       // LAP, UINT8   - reps performed
    private var _fAmrap;      // LAP, UINT8   - 1 = AMRAP set
    private var _fRestS;      // LAP, UINT16  - prescribed rest
    private var _fPeakG;      // LAP, FLOAT   - peak accel magnitude, G
    private var _fMeanG;      // LAP, FLOAT   - mean accel magnitude, G
    private var _fRepsEst;    // LAP, UINT8   - accel-derived rep estimate
    private var _fSamples;    // LAP, UINT16  - accel sample count for the set
    private var _fSetsDone;   // SESSION, UINT8
    private var _fVolumeLb;   // SESSION, UINT32
    private var _fAccelRate;  // SESSION, UINT8 - Hz actually requested
    private var _fHr;         // RECORD, UINT8   - bpm, one write per second
    private var _fHrAvg;      // SESSION, UINT8
    private var _fHrMax;      // SESSION, UINT8

    // ---- heart rate (Task 3) ----
    private var _hrTimer;
    private var _hrSum;
    private var _hrCount;
    private var _hrMax;

    // ---- accelerometer (Task 4) ----
    private var _accelRate;        // Hz actually requested from the sensor
    private var _accelSamples;
    private var _accelSumMag;      // sum of magnitude, milli-G
    private var _accelPeakMag;     // peak magnitude, milli-G
    private var _accelRepsEst;
    private var _accelAboveThreshold;

    function initialize() {
        _days = LiftPlan.days();
        // Only the main (non-deload) section is offered for now; the deload
        // days are in the plan and can be switched on later.
        _section = "";
        for (var i = 0; i < _days.size(); i++) {
            var d = _days[i] as Dictionary;
            var sec = d[:section] as String;
            if (_section.equals("")) {
                _section = sec;
            }
        }
        _dayIndex = 0;
        _exIndex = 0;
        _setIndex = 0;
        _started = false;
        _session = null;
        _startedAt = 0;
        _finalElapsedMs = -1;
        _restRemaining = 0;
        _restTotal = 0;
        _restTimer = null;
        _logged = [];
        _weights = [];
        _reps = [];
        _setsDone = 0;
        _setsTotal = 0;
        _program = "";
        _pendingBody = null;
        _pendingSets = 0;
        _programs = [];
        _programIndex = 0;
        _programId = "";
        _awaitingReps = false;
        _repsEditing = false;
        _activityNote = "";
        _syncNote = "";
        _lapsAdded = 0;
        _info = null;
        _historyIndex = 0;
        _sessionStopped = false;
        _exitPending = false;
        _exitTimer = null;
        _exitRequestedAt = 0;
        _fExercise = null;
        _fSetIndex = null;
        _fWeightLb = null;
        _fReps = null;
        _fAmrap = null;
        _fRestS = null;
        _fPeakG = null;
        _fMeanG = null;
        _fRepsEst = null;
        _fSamples = null;
        _fSetsDone = null;
        _fVolumeLb = null;
        _fAccelRate = null;
        _fHr = null;
        _fHrAvg = null;
        _fHrMax = null;
        _hrTimer = null;
        _hrSum = 0;
        _hrCount = 0;
        _hrMax = 0;
        _accelRate = 0;
        _resetAccelAccumulators();
        _resetEditable();
    }

    private function _resetAccelAccumulators() as Void {
        _accelSamples = 0;
        _accelSumMag = 0.0;
        _accelPeakMag = 0.0;
        _accelRepsEst = 0;
        _accelAboveThreshold = false;
    }

    // ------------------------------------------------------------- plan access

    // EVERY day in the plan: all week-blocks, deload included. The picker
    // distinguishes them by section label rather than hiding any.
    function dayCount() as Number { return _days.size(); }

    private function dayAt(index as Number) as Dictionary or Null {
        if (index < 0 or index >= _days.size()) { return null; }
        return _days[index] as Dictionary;
    }

    function section() as String { return _section; }

    function setProgram(name as String) as Void { _program = name; }

    function setComms(c as LiftComms) as Void { _comms = c; }

    // The day currently highlighted in the picker.
    function selectedDay() as Number { return _dayIndex; }

    function daySectionLabel(index as Number) as String {
        var d = dayAt(index);
        return d == null ? "" : d[:section] as String;
    }

    function hasChosenProgram() as Boolean {
        return Application.Storage.getValue("lift_program_id") != null;
    }

    function currentDay() as Dictionary or Null {
        return dayAt(_dayIndex);
    }

    function dayName(index as Number) as String {
        var d = dayAt(index);
        return d == null ? "-" : d[:name] as String;
    }

    // "Day 1" alone is ambiguous across week-blocks, so the picker shows the
    // section too: "Week 4 - Deload · Day 1".
    function dayLabel(index as Number) as String {
        var d = dayAt(index);
        if (d == null) { return "-"; }
        var sec = d[:section] as String;
        if (sec.equals("")) { return d[:name] as String; }
        return sec + " - " + (d[:name] as String);
    }

    // Every day in the plan, not just the first week-block.
    function allDays() as Boolean { return true; }

    function dayExerciseCount(index as Number) as Number {
        var d = dayAt(index);
        return d == null ? 0 : (d[:exercises] as Array).size();
    }

    function daySetCount(index as Number) as Number {
        var d = dayAt(index);
        if (d == null) { return 0; }
        var n = 0;
        var exs = d[:exercises] as Array;
        for (var i = 0; i < exs.size(); i++) {
            n += ((exs[i] as Dictionary)[:sets] as Array).size();
        }
        return n;
    }

    function currentExercises() as Array {
        var d = currentDay();
        return d == null ? [] : d[:exercises] as Array;
    }

    function currentExerciseIndex() as Number { return _exIndex; }

    // "" (not "done") when the cursor is past the end: "done" used to be
    // rendered as an exercise name by the info/history/stats screens and even
    // fetched from the backend (/watch/exercise?name=done).
    function currentExerciseName() as String {
        var exs = currentExercises();
        if (_exIndex >= exs.size()) { return ""; }
        return (exs[_exIndex] as Dictionary)[:name] as String;
    }

    function currentExerciseSetCount() as Number {
        var exs = currentExercises();
        if (_exIndex >= exs.size()) { return 0; }
        return ((exs[_exIndex] as Dictionary)[:sets] as Array).size();
    }

    function currentSetNumber() as Number { return _setIndex + 1; }

    // Bounds-safe: these are reachable from the info/menu screens, which can be
    // opened when the workout is finished and _exIndex is past the last exercise.
    function currentReps() as Number {
        if (_exIndex >= _reps.size() or _setIndex >= _reps[_exIndex].size()) { return 0; }
        return _reps[_exIndex][_setIndex];
    }

    function currentWeight() as Number {
        if (_exIndex >= _weights.size() or _setIndex >= _weights[_exIndex].size()) { return 0; }
        return _weights[_exIndex][_setIndex];
    }

    function currentRest() as Number {
        var exs = currentExercises();
        if (_exIndex >= exs.size()) { return 0; }
        return (exs[_exIndex] as Dictionary)[:rest] as Number;
    }

    function currentAmrap() as Boolean {
        var exs = currentExercises();
        if (_exIndex >= exs.size()) { return false; }
        if (_setIndex >= ((exs[_exIndex] as Dictionary)[:sets] as Array).size()) { return false; }
        if (_exIndex >= exs.size()) { return false; }
        var sets = (exs[_exIndex] as Dictionary)[:sets] as Array;
        if (_setIndex >= sets.size()) { return false; }
        return (sets[_setIndex] as Dictionary)[:amrap] as Boolean;
    }

    function isLogged(ex as Number, set as Number) as Boolean {
        if (ex >= _logged.size()) { return false; }
        if (set >= _logged[ex].size()) { return false; }
        return _logged[ex][set] as Boolean;
    }

    function isCurrentLogged() as Boolean { return isLogged(_exIndex, _setIndex); }

    function setsDone() as Number { return _setsDone; }
    function setsTotal() as Number { return _setsTotal; }
    function isStarted() as Boolean { return _started; }
    function isFinished() as Boolean { return _exIndex >= currentExercises().size(); }
    function setIndex() as Number { return _setIndex; }

    // ------------------------------------------------------------ session flow

    // Seed the editable copy of the plan so the user's weight edits stick.
    private function _resetEditable() as Void {
        _logged = [];
        _weights = [];
        _reps = [];
        _setsDone = 0;
        _setsTotal = 0;
        var exs = currentExercises();
        for (var i = 0; i < exs.size(); i++) {
            var sets = (exs[i] as Dictionary)[:sets] as Array;
            var lrow = [];
            var wrow = [];
            var rrow = [];
            for (var j = 0; j < sets.size(); j++) {
                var s = sets[j] as Dictionary;
                lrow.add(false);
                wrow.add(s[:weight] as Number);
                rrow.add(s[:reps] as Number);
                _setsTotal++;
            }
            _logged.add(lrow);
            _weights.add(wrow);
            _reps.add(rrow);
        }
    }

    function selectDay(index as Number) as Void {
        _dayIndex = index;
        _exIndex = 0;
        _setIndex = 0;
        _resetEditable();
        _restRemaining = 0;
        _restTotal = 0;
        _awaitingReps = false;
    }

    // Begin the session: start recording so Garmin Connect still gets an activity.
    function startWorkout() as Void {
        if (_started) { return; }
        // Starting a workout must never inherit a previous session's logged sets.
        // The grid used to survive a finish -> start cycle when the user pressed
        // START on the day picker without re-selecting the day (selectDay() is the
        // only other thing that resets it), so stale sets were re-uploaded as part
        // of the new workout - the 2026-09-18 test sent 8 Squat sets while only 6
        // laps were recorded. A restored mid-workout session returns above (it is
        // already _started), so this only clears a genuinely fresh start.
        _resetEditable();
        _started = true;
        _startedAt = Time.now().value();
        _finalElapsedMs = -1;
        _lapsAdded = 0;
        // A fresh session must never inherit a stashed body from a previous
        // (possibly much older, possibly failed) workout.
        clearPending();
        if (Toybox has :ActivityRecording) {
            _session = ActivityRecording.createSession({
                :name     => "Liftosaur - " + dayName(_dayIndex) + " (" + _section + ")",
                :sport    => Activity.SPORT_TRAINING,
                :subSport => Activity.SUB_SPORT_STRENGTH_TRAINING
            });
            if (_session == null) {
                _activityNote = "activity not started";
            } else {
                _session.start();
                _sessionStopped = false;
                _activityNote = "";
                createFitFields();
                startHrCapture();
                startAccel();
            }
        } else {
            _activityNote = "recording unsupported";
        }
        save();
    }

    // ------------------------------------------------------ FIT developer fields

    // Field ids are ours to choose and must stay stable across builds (they
    // identify the field to Garmin Connect). Developer fields are a bonus:
    // every call here is guarded so a failure never costs the workout itself.
    private function createFitFields() as Void {
        if (_session == null or !(Toybox has :FitContributor)) { return; }
        try {
            _fExercise = _session.createField("Exercise", 0, FitContributor.DATA_TYPE_STRING,
                {:mesgType => FitContributor.MESG_TYPE_LAP, :count => 32});
            _fSetIndex = _session.createField("SetIndex", 1, FitContributor.DATA_TYPE_UINT8,
                {:mesgType => FitContributor.MESG_TYPE_LAP});
            _fWeightLb = _session.createField("Weight", 2, FitContributor.DATA_TYPE_UINT16,
                {:mesgType => FitContributor.MESG_TYPE_LAP, :units => "lb"});
            _fReps = _session.createField("Reps", 3, FitContributor.DATA_TYPE_UINT8,
                {:mesgType => FitContributor.MESG_TYPE_LAP});
            _fAmrap = _session.createField("Amrap", 4, FitContributor.DATA_TYPE_UINT8,
                {:mesgType => FitContributor.MESG_TYPE_LAP});
            _fRestS = _session.createField("Rest", 5, FitContributor.DATA_TYPE_UINT16,
                {:mesgType => FitContributor.MESG_TYPE_LAP, :units => "s"});
            _fPeakG = _session.createField("PeakG", 6, FitContributor.DATA_TYPE_FLOAT,
                {:mesgType => FitContributor.MESG_TYPE_LAP, :units => "G"});
            _fMeanG = _session.createField("MeanG", 7, FitContributor.DATA_TYPE_FLOAT,
                {:mesgType => FitContributor.MESG_TYPE_LAP, :units => "G"});
            _fRepsEst = _session.createField("RepsEst", 8, FitContributor.DATA_TYPE_UINT8,
                {:mesgType => FitContributor.MESG_TYPE_LAP});
            _fSamples = _session.createField("Samples", 9, FitContributor.DATA_TYPE_UINT16,
                {:mesgType => FitContributor.MESG_TYPE_LAP});
            _fSetsDone = _session.createField("SetsDone", 10, FitContributor.DATA_TYPE_UINT8,
                {:mesgType => FitContributor.MESG_TYPE_SESSION});
            _fVolumeLb = _session.createField("Volume", 11, FitContributor.DATA_TYPE_UINT32,
                {:mesgType => FitContributor.MESG_TYPE_SESSION, :units => "lb"});
            _fAccelRate = _session.createField("AccelRate", 12, FitContributor.DATA_TYPE_UINT8,
                {:mesgType => FitContributor.MESG_TYPE_SESSION, :units => "Hz"});
            _fHr = _session.createField("HeartRate", 20, FitContributor.DATA_TYPE_UINT8,
                {:mesgType => FitContributor.MESG_TYPE_RECORD, :units => "bpm"});
            _fHrAvg = _session.createField("HeartRateAvg", 21, FitContributor.DATA_TYPE_UINT8,
                {:mesgType => FitContributor.MESG_TYPE_SESSION, :units => "bpm"});
            _fHrMax = _session.createField("HeartRateMax", 22, FitContributor.DATA_TYPE_UINT8,
                {:mesgType => FitContributor.MESG_TYPE_SESSION, :units => "bpm"});
        } catch (e) {
            // Developer fields are a bonus. Never let them cost a workout.
            System.println("Workout: createField failed: " + e.getErrorMessage());
        }
    }

    // One FIT lap per completed set, carrying what the set actually was, plus
    // that set's accelerometer summary. Values must be written IMMEDIATELY
    // before addLap(): the lap message snapshots them at that call.
    private function setLapFields() as Void {
        if (_session == null) { return; }
        try {
            if (_fExercise != null) { _fExercise.setData(currentExerciseName()); }
            if (_fSetIndex != null) { _fSetIndex.setData(_setIndex + 1); }
            if (_fWeightLb != null) { _fWeightLb.setData(_weights[_exIndex][_setIndex] as Number); }
            if (_fReps != null) { _fReps.setData(_reps[_exIndex][_setIndex] as Number); }
            if (_fAmrap != null) { _fAmrap.setData(currentAmrap() ? 1 : 0); }
            if (_fRestS != null) { _fRestS.setData(currentRest()); }
            if (_fPeakG != null) { _fPeakG.setData(_accelPeakMag / 1000.0); }
            if (_fMeanG != null) {
                var mean = (_accelSamples > 0) ? (_accelSumMag / _accelSamples) / 1000.0 : 0.0;
                _fMeanG.setData(mean);
            }
            if (_fRepsEst != null) { _fRepsEst.setData(_accelRepsEst); }
            if (_fSamples != null) { _fSamples.setData(_accelSamples); }
        } catch (e) {
            System.println("Workout: lap field write failed: " + e.getErrorMessage());
        }
        // Each lap is one set: the accelerometer accumulators reset for the next.
        _resetAccelAccumulators();
    }

    private function _computeVolumeLb() as Number {
        var vol = 0;
        for (var i = 0; i < _weights.size(); i++) {
            var wrow = _weights[i] as Array;
            for (var j = 0; j < wrow.size(); j++) {
                if (isLogged(i, j)) {
                    vol += (wrow[j] as Number) * (_reps[i][j] as Number);
                }
            }
        }
        return vol;
    }

    // Written just before _session.save() so the summary always reflects the
    // whole workout, not just the most recent set.
    private function writeSessionSummaryFields() as Void {
        if (_session == null) { return; }
        try {
            if (_fSetsDone != null) { _fSetsDone.setData(_setsDone); }
            if (_fVolumeLb != null) { _fVolumeLb.setData(_computeVolumeLb()); }
            if (_fAccelRate != null and _accelRate > 0) { _fAccelRate.setData(_accelRate); }
            if (_fHrAvg != null and _hrCount > 0) { _fHrAvg.setData(_hrSum / _hrCount); }
            if (_fHrMax != null) { _fHrMax.setData(_hrMax); }
        } catch (e) {
            System.println("Workout: session field write failed: " + e.getErrorMessage());
        }
    }

    // ------------------------------------------------------------- heart rate

    // Sensor.enableSensorEvents needs a listener method even though the actual
    // per-second HR write below reads Sensor.getInfo() directly on our own
    // timer - this just tells the OS the app wants sensor data flowing.
    function onSensorEvent(info as Sensor.Info) as Void {
    }

    private function startHrCapture() as Void {
        if (!(Toybox has :Sensor)) { return; }
        try {
            Sensor.enableSensorType(Sensor.SENSOR_ONBOARD_HEARTRATE);
        } catch (e) {
            System.println("Workout: enableSensorType failed: " + e.getErrorMessage());
        }
        try {
            Sensor.enableSensorEvents(method(:onSensorEvent));
        } catch (e) {
            System.println("Workout: enableSensorEvents failed: " + e.getErrorMessage());
        }
        try {
            _hrTimer = new Timer.Timer();
            _hrTimer.start(method(:hrTick), 1000, true);
        } catch (e) {
            System.println("Workout: HR timer start failed: " + e.getErrorMessage());
        }
    }

    // Guarantees a per-second HR field even on the sessions where the native
    // heart_rate stream is missing (the baseline showed 0% native HR on some
    // app-recorded activities).
    function hrTick() as Void {
        if (!(Toybox has :Sensor)) { return; }
        try {
            var info = Sensor.getInfo();
            if (info != null and info.heartRate != null) {
                var hr = info.heartRate as Number;
                if (hr > 0 and hr < 250) {
                    if (_fHr != null) { _fHr.setData(hr); }
                    _hrSum += hr;
                    _hrCount++;
                    if (hr > _hrMax) { _hrMax = hr; }
                }
            }
        } catch (e) {
            // A bad/missing reading must never break the workout.
        }
    }

    // ---------------------------------------------------------- accelerometer

    // The public Sensor API caps this well below 100 Hz; ask the system for
    // its maximum and clamp to 25 Hz so the rate matches the contract in docs/05.
    private function startAccel() as Void {
        if (!(Toybox has :Sensor)) { return; }
        try {
            var maxRate = Sensor.getMaxSampleRateForSensorType(:accelerometer);
            var rate = 25;
            if (maxRate != null and (maxRate as Number) < rate) { rate = maxRate as Number; }
            _accelRate = rate;
            Sensor.registerSensorDataListener(method(:onAccelData),
                {:period => 1, :accelerometer => {:enabled => true, :sampleRate => rate}});
        } catch (e) {
            System.println("Workout: accel registration failed: " + e.getErrorMessage());
        }
    }

    // Accumulates per set: sample count, sum/peak of the acceleration
    // magnitude, and a simple rep estimate from magnitude peaks above a
    // hysteresis band. Reset happens in setLapFields() (each lap is one set).
    function onAccelData(sensorData as Sensor.SensorData) as Void {
        try {
            var accel = sensorData.accelerometerData;
            if (accel == null) { return; }
            var xs = accel.x;
            var ys = accel.y;
            var zs = accel.z;
            if (xs == null or ys == null or zs == null) { return; }
            var n = xs.size();
            for (var i = 0; i < n; i++) {
                var x = xs[i] as Number;
                var y = ys[i] as Number;
                var z = zs[i] as Number;
                var mag = Math.sqrt((x * x + y * y + z * z).toFloat());
                _accelSamples++;
                _accelSumMag += mag;
                if (mag > _accelPeakMag) { _accelPeakMag = mag; }
                if (_accelAboveThreshold) {
                    if (mag < ACCEL_LOW_MILLI_G) { _accelAboveThreshold = false; }
                } else if (mag > ACCEL_HIGH_MILLI_G) {
                    _accelAboveThreshold = true;
                    _accelRepsEst++;
                }
            }
        } catch (e) {
            // A bad sample batch must never break the workout.
        }
    }

    // Adjust the current set's weight by delta (5 lb steps in the UI).
    function adjustWeight(delta as Number) as Void {
        if (isFinished()) { return; }
        var w = _weights[_exIndex][_setIndex] as Number;
        var nw = w + delta;
        if (nw < 0) { nw = 0; }
        _weights[_exIndex][_setIndex] = nw;
    }

    function adjustReps(delta as Number) as Void {
        if (isFinished()) { return; }
        var r = _reps[_exIndex][_setIndex] as Number;
        var nr = r + delta;
        if (nr < 1) { nr = 1; }
        _reps[_exIndex][_setIndex] = nr;
    }

    // SELECT during rest must ONLY end the rest. Previously it fell through to
    // completeSet(), which logged a set that had not happened yet and started a
    // fresh rest - so "skipping" silently ate the next set.
    function skipRest() as Void {
        stopRest();
        WatchUi.requestUpdate();
    }

    // The AMRAP set drives 5/3/1 progression, so its ACTUAL reps matter. Rather
    // than log the target, the app asks: adjust with a swipe, confirm with
    // SELECT. Only gestures proven to work on this device are used.
    function isAwaitingReps() as Boolean { return _awaitingReps; }

    function beginRepsEntry() as Void {
        _awaitingReps = true;
        WatchUi.requestUpdate();
    }

    // Confirm the reps just entered and finally log the set.
    function confirmReps() as Void {
        if (!_awaitingReps) { return; }
        _awaitingReps = false;
        completeSet();
    }

    // The only structured marker this device supports: addSets()/SetType do not
    // exist on the Venu 2S (verified against its API file), so each completed set
    // becomes a LAP. That at least gives the activity real content and per-set
    // timing in Garmin Connect.
    private function markLap() as Void {
        if (_session == null) { return; }
        setLapFields();
        _session.addLap();
        _lapsAdded++;
    }

    // Mark the current set done and move on, starting the rest countdown.
    function completeSet() as Void {
        if (isFinished()) { return; }
        // An AMRAP set asks for its actual reps first (unless we are confirming).
        if (currentAmrap() and !isLogged(_exIndex, _setIndex) and !_awaitingReps) {
            beginRepsEntry();
            return;
        }
        _awaitingReps = false;
        if (!isLogged(_exIndex, _setIndex)) {
            _logged[_exIndex][_setIndex] = true;
            recountLogged();
            markLap();
            // Push the workout-so-far to Liftosaur. Decision #3: silent -
            // postLiveSet() never surfaces failure and never blocks this call.
            if (_comms != null) { _comms.postLiveSet(); }
        }
        var rest = currentRest();
        // advance within the exercise, then to the next exercise
        if (_setIndex + 1 < currentExerciseSetCount()) {
            _setIndex++;
        } else {
            _exIndex++;
            _setIndex = 0;
        }
        if (!isFinished() && rest > 0) {
            startRest(rest);
        }
        save();
        WatchUi.requestUpdate();
    }

    // Step back a set (mis-tap recovery).
    function previousSet() as Void {
        if (_setIndex > 0) {
            _setIndex--;
        } else if (_exIndex > 0) {
            _exIndex--;
            _setIndex = currentExerciseSetCount() - 1;
        }
        save();
        WatchUi.requestUpdate();
    }

    // BACK / menu navigation. Stepping back un-logs the set so it can be redone;
    // stepping forward via the menu skips WITHOUT logging (the user may have
    // switched exercises), which completeSet() deliberately does not do.
    // ---- the exercise list (options -> View workout) ----
    function exerciseNameAt(index as Number) as String {
        var exs = currentExercises();
        if (index < 0 or index >= exs.size()) { return "-"; }
        return (exs[index] as Dictionary)[:name] as String;
    }

    function exerciseIsDone(index as Number) as Boolean {
        var exs = currentExercises();
        if (index < 0 or index >= exs.size()) { return false; }
        var sets = (exs[index] as Dictionary)[:sets] as Array;
        for (var j = 0; j < sets.size(); j++) {
            if (!isLogged(index, j)) { return false; }
        }
        return sets.size() > 0;
    }

    function jumpToExercise(index as Number) as Void {
        if (index < 0 or index >= currentExercises().size()) { return; }
        _exIndex = index;
        _setIndex = 0;
        _awaitingReps = false;
        save();
        WatchUi.requestUpdate();
    }

    // Every SET of the day, flattened, so the list can be per-set rather than
    // per-exercise: "Squat 220 x 5" is what you actually need to find.
    function setCount() as Number {
        var n = 0;
        var exs = currentExercises();
        for (var i = 0; i < exs.size(); i++) {
            n += ((exs[i] as Dictionary)[:sets] as Array).size();
        }
        return n;
    }

    // Flat index over every set: [exercise index, set index]
    private function setRefAt(flat as Number) as Array {
        var exs = currentExercises();
        var k = 0;
        for (var i = 0; i < exs.size(); i++) {
            var sn = ((exs[i] as Dictionary)[:sets] as Array).size();
            if (flat < k + sn) { return [i, flat - k]; }
            k += sn;
        }
        return [0, 0];
    }

    function setLabelAt(flat as Number) as String {
        var ref = setRefAt(flat);
        var ei = ref[0] as Number;
        var si = ref[1] as Number;
        var exs = currentExercises();
        if (ei >= exs.size()) { return "-"; }
        var name = (exs[ei] as Dictionary)[:name] as String;
        var reps = _reps[ei][si] as Number;
        var amrap = (((exs[ei] as Dictionary)[:sets] as Array)[si] as Dictionary)[:amrap] as Boolean;
        return name + "  " + (_weights[ei][si] as Number) + " x " + reps +
               (amrap ? "+" : "");
    }

    function setSublabelAt(flat as Number) as String {
        var ref = setRefAt(flat);
        var ei = ref[0] as Number;
        var si = ref[1] as Number;
        var exs = currentExercises();
        var sn = ((exs[ei] as Dictionary)[:sets] as Array).size();
        var mark = isLogged(ei, si) ? "done" : "todo";
        if (ei == _exIndex and si == _setIndex) { mark += "  now"; }
        return "set " + (si + 1) + " of " + sn + "   " + mark;
    }

    function jumpToSet(flat as Number) as Void {
        var ref = setRefAt(flat);
        _exIndex = ref[0] as Number;
        _setIndex = ref[1] as Number;
        _awaitingReps = false;
        save();
        WatchUi.requestUpdate();
    }

    // ---- exercise info (previous session, from the backend) ----
    function setExerciseInfo(dict as Dictionary or Null) as Void {
        _info = dict;
        _historyIndex = 0;   // fresh data: drop any stale selection into the old list
    }

    function infoLoaded() as Boolean { return _info != null; }

    // "5x120  3x140  1x155" — grouped, because that is how it scrolls by
    function infoSetsText() as String {
        if (_info == null) { return ""; }
        var last = _info["last"];
        if (!(last instanceof Dictionary)) { return "no previous session"; }
        var sets = (last as Dictionary)["sets"];
        if (!(sets instanceof Array)) { return ""; }
        var out = "";
        var prevW = -1;
        var prevR = -1;
        var run = 0;
        for (var i = 0; i <= (sets as Array).size(); i++) {
            var w = -1;
            var r = -1;
            if (i < (sets as Array).size()) {
                var st = (sets as Array)[i] as Dictionary;
                w = st["weight"] as Number;
                r = st["reps"] as Number;
            }
            if (w == prevW and r == prevR) {
                run++;
            } else {
                if (run > 0) {
                    if (out.length() > 0) { out += "   "; }
                    out += run + "x" + prevR + " @ " + prevW;
                }
                prevW = w; prevR = r; run = 1;
            }
        }
        return out;
    }

    // Up to three short lines of "3x10 @ 95" groups. Built here, not in the
    // view: String.find(value, startIndex) does not exist on this device and
    // calling it threw "Too Many Arguments Error" inside onUpdate.
    function infoSetLines() as Array {
        var lines = [];
        if (_info == null) { return lines; }
        var last = _info["last"];
        if (!(last instanceof Dictionary)) { return lines; }
        var sets = (last as Dictionary)["sets"];
        if (!(sets instanceof Array)) { return lines; }
        var cur = "";
        var prevW = -1;
        var prevR = -1;
        var run = 0;
        for (var i = 0; i <= (sets as Array).size(); i++) {
            var w = -1;
            var r = -1;
            if (i < (sets as Array).size()) {
                var st = (sets as Array)[i] as Dictionary;
                w = st["weight"] as Number;
                r = st["reps"] as Number;
            }
            if (w == prevW and r == prevR) {
                run++;
            } else {
                if (run > 0) {
                    var grp = run + "x" + prevR + " @ " + prevW;
                    if ((cur.length() + grp.length() + 3) > 20) {
                        if (!cur.equals("")) { lines.add(cur); }
                        cur = grp;
                    } else {
                        cur = cur.equals("") ? grp : cur + "   " + grp;
                    }
                }
                prevW = w; prevR = r; run = 1;
            }
        }
        if (!cur.equals("")) { lines.add(cur); }
        return lines;
    }

    function infoDateText() as String {
        if (_info == null) { return ""; }
        var last = _info["last"];
        if (!(last instanceof Dictionary)) { return ""; }
        var d = (last as Dictionary)["date"];
        if (!(d instanceof String)) { return ""; }
        var s = d as String;
        if (s.length() > 10) { return s.substring(0, 10); }
        return s;
    }

    function infoTopText() as String {
        if (_info == null) { return ""; }
        var last = _info["last"];
        if (!(last instanceof Dictionary)) { return ""; }
        return "top " + ((last as Dictionary)["top_weight"] as Number) + " lb";
    }

    // Collapse consecutive equal (weight, reps) sets into "NxR W" groups (no
    // units - callers add "lb" and their own spacing/line-wrapping). Shared by
    // historySublabel() and historyDetailLines() so this run-collapsing logic
    // exists in exactly one place instead of being copy-pasted again.
    private function _groupRuns(sets as Array) as Array {
        var out = [];
        var prevW = -1;
        var prevR = -1;
        var run = 0;
        for (var j = 0; j <= sets.size(); j++) {
            var w = -1;
            var r = -1;
            if (j < sets.size()) {
                var st = sets[j] as Dictionary;
                w = st["weight"] as Number;
                r = st["reps"] as Number;
            }
            if (w == prevW and r == prevR) {
                run++;
            } else {
                if (run > 0) { out.add(run + "x" + prevR + " " + prevW); }
                prevW = w; prevR = r; run = 1;
            }
        }
        return out;
    }

    // ---- history list (one row per session, Task 7) ----
    private function _historyRecordAt(index as Number) as Dictionary or Null {
        if (_info == null) { return null; }
        var rec = _info["recent"];
        if (!(rec instanceof Array)) { return null; }
        if (index < 0 or index >= (rec as Array).size()) { return null; }
        return (rec as Array)[index] as Dictionary;
    }

    private function _monthDayLabel(date as String) as String {
        // "YYYY-MM-DD ..." -> "Sep 10"
        if (date.length() < 10) { return date; }
        var months = ["Jan", "Feb", "Mar", "Apr", "May", "Jun",
                      "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"];
        var mm = (date.substring(5, 7) as String).toNumber();
        var dd = date.substring(8, 10);
        if (mm == null or mm < 1 or mm > 12) { return date.substring(5, 10); }
        return (months[mm - 1] as String) + " " + dd;
    }

    function historyCount() as Number {
        if (_info == null) { return 0; }
        var rec = _info["recent"];
        return (rec instanceof Array) ? (rec as Array).size() : 0;
    }

    // "Sep 10  -  top 305"
    function historyLabel(index as Number) as String {
        var rec = _historyRecordAt(index);
        if (rec == null) { return "-"; }
        var date = _monthDayLabel(rec["date"] as String);
        return date + "  -  top " + (rec["top_weight"] as Number);
    }

    // Compact, <= 22 chars: "5x240  3x275  2x305"
    function historySublabel(index as Number) as String {
        var rec = _historyRecordAt(index);
        if (rec == null) { return ""; }
        var groups = _groupRuns(rec["sets"] as Array);
        var out = "";
        for (var i = 0; i < groups.size(); i++) {
            var g = groups[i] as String;
            if ((out.length() + g.length() + 2) > 22) { break; }
            out += out.equals("") ? g : "  " + g;
        }
        return out;
    }

    // That session's full grouped sets, one line per group, <= 20 chars.
    function historyDetailLines(index as Number) as Array {
        var lines = [];
        var rec = _historyRecordAt(index);
        if (rec == null) { return lines; }
        var groups = _groupRuns(rec["sets"] as Array);
        var cur = "";
        for (var i = 0; i < groups.size(); i++) {
            var g = groups[i] as String;
            if ((cur.length() + g.length() + 3) > 20) {
                if (!cur.equals("")) { lines.add(cur); }
                cur = g;
            } else {
                cur = cur.equals("") ? g : cur + "   " + g;
            }
        }
        if (!cur.equals("")) { lines.add(cur); }
        return lines;
    }

    function historyDateText(index as Number) as String {
        var rec = _historyRecordAt(index);
        return rec == null ? "" : _monthDayLabel(rec["date"] as String);
    }

    function historyTopText(index as Number) as String {
        var rec = _historyRecordAt(index);
        return rec == null ? "" : "top " + (rec["top_weight"] as Number) + " lb";
    }

    function historyE1rmText(index as Number) as String {
        var rec = _historyRecordAt(index);
        return rec == null ? "" : "e1rm " + (rec["e1rm"] as Number) + " lb";
    }

    function historyVolumeText(index as Number) as String {
        var rec = _historyRecordAt(index);
        return rec == null ? "" : "volume " + (rec["volume"] as Number) + " lb";
    }

    function selectHistory(index as Number) as Void { _historyIndex = index; }
    function selectedHistory() as Number { return _historyIndex; }

    function infoVolumeText() as String {
        if (_info == null) { return ""; }
        var last = _info["last"];
        if (!(last instanceof Dictionary)) { return ""; }
        var sets = (last as Dictionary)["sets"];
        if (!(sets instanceof Array)) { return ""; }
        var vol = 0;
        for (var i = 0; i < (sets as Array).size(); i++) {
            var st = (sets as Array)[i] as Dictionary;
            vol += (st["weight"] as Number) * (st["reps"] as Number);
        }
        return "volume " + vol + " lb";
    }

    function infoE1rmText() as String {
        if (_info == null) { return ""; }
        var last = _info["last"];
        if (!(last instanceof Dictionary)) { return ""; }
        return "e1rm " + ((last as Dictionary)["e1rm"] as Number) + " lb";
    }

    // What the plan prescribes right now, for the info screen.
    function targetText() as String {
        if (isFinished()) { return "session complete"; }
        return currentWeight() + " lb x " + currentReps() +
               (currentAmrap() ? "+" : "") + "   rest " + currentRest() + "s";
    }

    // Session progress as a fraction, for the ring.
    function setProgress() as Float {
        var total = _setsTotal;
        return total <= 0 ? 0.0 : _setsDone.toFloat() / total.toFloat();
    }

    // The reps the PROGRAM prescribed for this set (what _reps started as), so
    // the adjust screen can show "target 5+" next to the edited value.
    function plannedReps() as Number {
        var exs = currentExercises();
        if (_exIndex >= exs.size()) { return 0; }
        var sets = (exs[_exIndex] as Dictionary)[:sets] as Array;
        if (_setIndex >= sets.size()) { return 0; }
        return (sets[_setIndex] as Dictionary)[:reps] as Number;
    }

    // Ask the backend for this exercise's previous session (info screen).
    function requestExerciseInfo() as Void {
        if (isFinished()) {
            // Nothing to look up; the views show the session summary instead.
            _info = null;
            WatchUi.requestUpdate();
            return;
        }
        if (_comms != null) { _comms.fetchExerciseInfo(currentExerciseName()); }
    }

    // The compact payload to POST at finish: a stashed retry (_pendingBody set,
    // no reliable _startedAt left) sends the 4-field pendingText(); a fresh
    // end-of-workout save sends the 5-field livePayload() so the finish write
    // keeps the same stable timestamp the live-sync updates used.
    function outgoingPayload() as String or Null {
        if (_pendingBody != null) { return pendingText(); }
        return livePayload();
    }

    // "Next set": logs the current set if it has not been logged yet (the
    // natural meaning of done-and-on), otherwise just advances.
    function advance() as Void {
        if (isFinished()) { finishWorkout(); return; }
        if (isLogged(_exIndex, _setIndex)) { stepForward(); }
        else { completeSet(); }
    }

    // Which field the edit screen's swipes are changing.
    function adjustFieldIsWeight() as Boolean { return !_repsEditing; }
    function toggleAdjustField() as Void { _repsEditing = !_repsEditing; }

    function canGoBack() as Boolean {
        return (_setIndex > 0) or (_exIndex > 0);
    }

    function stepForward() as Void {
        if (isFinished()) { return; }
        _awaitingReps = false;
        if (_setIndex + 1 < currentExerciseSetCount()) {
            _setIndex++;
        } else {
            _exIndex++;
            _setIndex = 0;
        }
        save();
        WatchUi.requestUpdate();
    }

    function skipExercise() as Void {
        if (isFinished()) { return; }
        _exIndex++;
        _setIndex = 0;
        save();
        WatchUi.requestUpdate();
    }

    // ------------------------------------------------------------------- rest

    function startRest(seconds as Number) as Void {
        // The user can add/remove rest with a swipe, so clamp at zero.
        if (seconds <= 0) {
            stopRest();
            WatchUi.requestUpdate();
            return;
        }
        _restTotal = seconds;
        _restRemaining = seconds;
        if (_restTimer == null) {
            _restTimer = new Timer.Timer();
        }
        _restTimer.stop();
        _restTimer.start(method(:onRestTick), 1000, true);
    }

    function onRestTick() as Void {
        if (_restRemaining > 0) {
            _restRemaining--;
        }
        if (_restRemaining == 0) {
            stopRest();
            if (Toybox has :Attention) {
                Attention.vibrate([new Attention.VibeProfile(100, 300)]);
            }
        }
        WatchUi.requestUpdate();
    }

    function stopRest() as Void {
        if (_restTimer != null) {
            _restTimer.stop();
        }
        _restRemaining = 0;
    }

    function restRemaining() as Number { return _restRemaining; }
    function restTotal() as Number { return _restTotal; }
    function isResting() as Boolean { return _restRemaining > 0; }

    // ----------------------------------------------------------- persistence

    // Storage accepts scalars and 1-D arrays, but not nested arrays, and its
    // generics are strict. Serialising to a String sidesteps both: "135,170,..."
    // for numbers and "0110..." for the logged flags.
    private function joinNumbers(grid as Array) as String {
        var out = "";
        var first = true;
        for (var i = 0; i < grid.size(); i++) {
            var row = grid[i] as Array;
            for (var j = 0; j < row.size(); j++) {
                if (!first) { out += ","; }
                out += (row[j] as Number).toString();
                first = false;
            }
        }
        return out;
    }

    private function joinBooleans(grid as Array) as String {
        var out = "";
        for (var i = 0; i < grid.size(); i++) {
            var row = grid[i] as Array;
            for (var j = 0; j < row.size(); j++) {
                out += ((row[j] as Boolean) ? "1" : "0");
            }
        }
        return out;
    }

    private function splitNumbers(str as String, grid as Array) as Void {
        if (str == null || str.equals("")) { return; }
        // String.split() is not available on this runtime, so tokenise by hand.
        var toks = [];
        var start = 0;
        var len = str.length();
        for (var i = 0; i <= len; i++) {
            var atEnd = (i == len);
            if (atEnd || (str.substring(i, i + 1) as String).equals(",")) {
                if (i > start) { toks.add(str.substring(start, i)); }
                start = i + 1;
            }
        }
        var k = 0;
        for (var gi = 0; gi < grid.size(); gi++) {
            var row = grid[gi] as Array;
            for (var gj = 0; gj < row.size(); gj++) {
                if (k < toks.size()) {
                    var v = (toks[k] as String).toNumber();
                    if (v != null) { row[gj] = v; }
                }
                k++;
            }
        }
    }

    private function splitBooleans(str as String, grid as Array) as Void {
        if (str == null || str.equals("")) { return; }
        var k = 0;
        for (var i = 0; i < grid.size(); i++) {
            var row = grid[i] as Array;
            for (var j = 0; j < row.size(); j++) {
                if (k < str.length()) {
                    row[j] = (str.substring(k, k + 1) as String).equals("1");
                }
                k++;
            }
        }
    }

    function save() as Void {
        Application.Storage.setValue("lift_day", _dayIndex);
        Application.Storage.setValue("lift_ex", _exIndex);
        Application.Storage.setValue("lift_set", _setIndex);
        Application.Storage.setValue("lift_started", _started);
        Application.Storage.setValue("lift_started_at", _startedAt);
        Application.Storage.setValue("lift_done", _setsDone);
        Application.Storage.setValue("lift_total", _setsTotal);
        Application.Storage.setValue("lift_weights", joinNumbers(_weights));
        Application.Storage.setValue("lift_reps", joinNumbers(_reps));
        Application.Storage.setValue("lift_logged", joinBooleans(_logged));
    }

    // Restore an interrupted session, if the plan still matches.
    function restore() as Boolean {
        var pid = Application.Storage.getValue("lift_program_id");
        if (pid != null) { _programId = pid as String; }
        var day = Application.Storage.getValue("lift_day");
        if (day == null) { return false; }
        var d = day as Number;
        if (d >= dayCount()) { return false; }
        _dayIndex = d;
        _exIndex = Application.Storage.getValue("lift_ex") as Number;
        _setIndex = Application.Storage.getValue("lift_set") as Number;
        _started = Application.Storage.getValue("lift_started") as Boolean;
        var startedAt = Application.Storage.getValue("lift_started_at");
        _startedAt = (startedAt != null) ? (startedAt as Number) : 0;
        _setsDone = Application.Storage.getValue("lift_done") as Number;
        _setsTotal = Application.Storage.getValue("lift_total") as Number;
        var w = Application.Storage.getValue("lift_weights");
        if (w != null) { splitNumbers(w as String, _weights); }
        var r = Application.Storage.getValue("lift_reps");
        if (r != null) { splitNumbers(r as String, _reps); }
        var l = Application.Storage.getValue("lift_logged");
        if (l != null) { splitBooleans(l as String, _logged); }
        // Derive the counter from the restored grid instead of trusting the
        // stored "lift_done": a restored session used to keep the PREVIOUS
        // session's count, so the summary and the SetsDone field read "16 sets"
        // for an 11-set workout.
        recountLogged();
        return true;
    }

    // _setsDone is always the number of true flags in _logged - one source of
    // truth, so no path can drift again.
    private function recountLogged() as Void {
        var n = 0;
        for (var i = 0; i < _logged.size(); i++) {
            var row = _logged[i] as Array;
            for (var j = 0; j < row.size(); j++) {
                if (row[j] as Boolean) { n++; }
            }
        }
        _setsDone = n;
    }

    function clearSaved() as Void {
        Application.Storage.deleteValue("lift_day");
        Application.Storage.deleteValue("lift_ex");
        Application.Storage.deleteValue("lift_set");
        Application.Storage.deleteValue("lift_started");
        Application.Storage.deleteValue("lift_started_at");
        Application.Storage.deleteValue("lift_done");
        Application.Storage.deleteValue("lift_total");
        Application.Storage.deleteValue("lift_weights");
        Application.Storage.deleteValue("lift_reps");
        Application.Storage.deleteValue("lift_logged");
        // Live-sync bookkeeping: a stale id here would make some later,
        // unrelated workout silently UPDATE this one's Liftosaur record.
        Application.Storage.deleteValue("lift_live_record");
        Application.Storage.deleteValue("lift_pending_record");
    }

    // ---------------------------------------------------------- program choice

    // Programs come from the backend as JSON dicts (string keys): id, name,
    // isCurrent. The chosen one is persisted so a restart keeps the selection.
    function setPrograms(list as Array) as Void {
        _programs = list;
        _programIndex = 0;
        for (var i = 0; i < _programs.size(); i++) {
            var p = _programs[i] as Dictionary;
            var cur = p["isCurrent"];
            if (cur instanceof Boolean and (cur as Boolean)) {
                _programIndex = i;
                break;
            }
        }
    }

    function programCount() as Number { return _programs.size(); }

    function programLabel(index as Number) as String {
        if (index < 0 or index >= _programs.size()) { return "-"; }
        var p = _programs[index] as Dictionary;
        var name = p["name"] as String;
        var cur = p["isCurrent"];
        if (cur instanceof Boolean and (cur as Boolean)) {
            return name + " (current)";
        }
        return name;
    }

    function programIdAt(index as Number) as String {
        if (index < 0 or index >= _programs.size()) { return "current"; }
        return (_programs[index] as Dictionary)["id"] as String;
    }

    function selectedProgramIndex() as Number { return _programIndex; }

    function selectProgramIndex(index as Number) as Void { _programIndex = index; }

    // Commit the highlighted program and remember it across restarts.
    function chooseSelectedProgram() as Void {
        _programId = programIdAt(_programIndex);
        Application.Storage.setValue("lift_program_id", _programId);
        Application.Storage.setValue("lift_program_name", programLabel(_programIndex));
    }

    function chosenProgramId() as String {
        if (_programId == null or _programId.equals("")) { return "current"; }
        return _programId;
    }

    // After choosing a different program, pull its plan in the background.
    function reloadPlan() as Void {
        if (_comms != null) { _comms.fetchPlan(chosenProgramId()); }
    }

    function chosenProgramName() as String {
        var n = Application.Storage.getValue("lift_program_name");
        if (n == null) { return ""; }
        return n as String;
    }

    // ------------------------------------------------------------ backend sync

    // Swap in the plan fetched from the backend. Refused once a workout is
    // under way: replacing the plan mid-session would invalidate the cursor.
    function adoptRemotePlan(days as Array) as Boolean {
        if (_started or days.size() == 0) { return false; }
        var keepDay = _dayIndex;   // do not yank the picker back while choosing
        _days = days;
        _section = "";
        for (var i = 0; i < _days.size(); i++) {
            var sec = (_days[i] as Dictionary)[:section] as String;
            if (_section.equals("")) { _section = sec; }
        }
        var n = dayCount();
        _dayIndex = (keepDay < n) ? keepDay : 0;
        _exIndex = 0;
        _setIndex = 0;
        _resetEditable();
        return true;
    }

    // The body for POST /api/v1/watch/workout: only sets the user actually
    // completed, in the order they were trained.
    // Scans for the last run of digits in a string and returns it as a Number
    // (0 if there are none) - "Week 3" -> 3, "Day 5 - Light Pump (Wed)" -> 5.
    private function _trailingNumber(s as String) as Number {
        var len = s.length();
        var end = -1;
        var start = -1;
        for (var i = len - 1; i >= 0; i--) {
            var ch = s.substring(i, i + 1);
            var isDigit = ch.equals("0") or ch.equals("1") or ch.equals("2") or
                         ch.equals("3") or ch.equals("4") or ch.equals("5") or
                         ch.equals("6") or ch.equals("7") or ch.equals("8") or ch.equals("9");
            if (isDigit) {
                if (end == -1) { end = i; }
                start = i;
            } else if (end != -1) {
                break;
            }
        }
        if (end == -1) { return 0; }
        var n = s.substring(start, end + 1).toNumber();
        return (n == null) ? 0 : n;
    }

    // "Week 3" -> 3. The day list spans every week-block, so the index into it
    // is NOT the day of the week: a Week-3 day used to be uploaded as week 1,
    // dayInWeek 15 and landed in the wrong slot in Liftosaur.
    function weekNumber() as Number {
        var d = currentDay();
        if (d == null) { return 1; }
        var sec = d[:section] as String;
        var n = _trailingNumber(sec);
        return n > 0 ? n : 1;
    }

    function dayInWeek() as Number {
        var d = currentDay();
        if (d == null) { return 1; }
        var n = _trailingNumber(d[:name] as String);
        return n > 0 ? n : 1;
    }

    function buildWorkoutBody() as Dictionary or Null {
        var sets = [];
        var exs = currentExercises();
        for (var i = 0; i < exs.size(); i++) {
            var name = (exs[i] as Dictionary)[:name] as String;
            var planSets = (exs[i] as Dictionary)[:sets] as Array;
            // Defensive: _weights/_reps are sized by the plan that was active
            // when the workout began. A restored session or a swapped plan can
            // leave them shorter, and indexing blindly crashed the save.
            if (i >= _weights.size() or i >= _reps.size()) { continue; }
            if (planSets.size() > (_weights[i] as Array).size()) { continue; }
            for (var j = 0; j < planSets.size(); j++) {
                if (!isLogged(i, j)) { continue; }
                sets.add({
                    :exercise => name,
                    :weight => _weights[i][j] as Number,
                    :reps => _reps[i][j] as Number,
                    :amrap => (planSets[j] as Dictionary)[:amrap] as Boolean
                });
            }
        }
        if (sets.size() == 0) { return null; }
        return {
            :day => dayName(_dayIndex),
            :section => _section,
            :program => _program,
            :week => weekNumber(),
            :day_in_week => dayInWeek(),
            :duration_s => elapsedMs() / 1000,
            :sets => sets
        };
    }

    // Shared compact-string builder for pendingText()/livePayload():
    // "day|section|program|duration[|startedAt];Ex|w|r|a;Ex|w|r|a"
    // startedAt (the live-sync header field) is only appended when given.
    private function _compact(body as Dictionary, startedAt as Number or Null) as String {
        var out = (body[:day] as String) + "|" + (body[:section] as String) + "|" +
                  (body[:program] as String) + "|" + (body[:duration_s] as Number);
        if (startedAt != null) {
            out += "|" + startedAt;
        }
        var sets = body[:sets] as Array;
        for (var i = 0; i < sets.size(); i++) {
            var s = sets[i] as Dictionary;
            out += ";" + (s[:exercise] as String) + "|" + (s[:weight] as Number) + "|" +
                   (s[:reps] as Number) + "|" + ((s[:amrap] as Boolean) ? "1" : "0");
        }
        return out;
    }

    // Compact stash for a workout that could not be uploaded:
    // "day|section|program|duration;Ex|w|r|a;Ex|w|r|a"
    function pendingText() as String or Null {
        var body = buildWorkoutBodyOrPending();
        if (body == null) { return null; }
        return _compact(body, null);
    }

    // Live-sync payload: the same compact string as pendingText(), but always
    // built from the CURRENT cursor (never a reloaded stash) and carrying the
    // wall-clock session start as the 5th header field, so the backend can
    // keep the live record's timestamp fixed across every update instead of
    // re-dating it on each completed set.
    function livePayload() as String or Null {
        var body = buildWorkoutBody();
        if (body == null) { return null; }
        return _compact(body, _startedAt);
    }

    // Rebuild a stashed workout so it can be posted again.
    function loadPendingText(text as String) as Boolean {
        var i = text.find(";");
        if (i == null) { return false; }
        var head = text.substring(0, i);
        var fields = _split(head, "|");
        if (fields.size() < 4) { return false; }
        var sets = [];
        var rest = text.substring(i + 1, text.length());
        var parts = _split(rest, ";");
        for (var k = 0; k < parts.size(); k++) {
            var f = _split(parts[k] as String, "|");
            if (f.size() < 4) { continue; }
            sets.add({:exercise => f[0], :weight => (f[1] as String).toNumber(),
                      :reps => (f[2] as String).toNumber(),
                      :amrap => (f[3] as String).equals("1")});
        }
        if (sets.size() == 0) { return false; }
        // A stashed workout has no day context left (pendingText() doesn't
        // carry week/day_in_week), so this can't call weekNumber()/dayInWeek()
        // - leave the placeholders as-is deliberately.
        _pendingBody = {
            :day => fields[0], :section => fields[1], :program => fields[2],
            :duration_s => (fields[3] as String).toNumber(),
            :week => 1, :day_in_week => 1, :sets => sets
        };
        _pendingSets = sets.size();
        return true;
    }

    function buildWorkoutBodyOrPending() as Dictionary or Null {
        if (_pendingBody != null) { return _pendingBody; }
        return buildWorkoutBody();
    }

    function pendingSetCount() as Number { return _pendingSets; }

    // The stashed body is cleared once it has actually been posted. It used to
    // live for the rest of the run, so after a single retry EVERY later
    // postWorkout() re-sent the old workout and the new one was never uploaded.
    function clearPending() as Void {
        _pendingBody = null;
        _pendingSets = 0;
    }

    private function _split(s as String, sep as String) as Array {
        var out = [];
        var start = 0;
        var len = s.length();
        for (var i = 0; i <= len; i++) {
            var atEnd = (i == len);
            if (atEnd or (s.substring(i, i + 1) as String).equals(sep)) {
                out.add(s.substring(start, i));
                start = i + 1;
            }
        }
        return out;
    }

    // ------------------------------------------------------------------ finish

    // Stop recording and let the user keep or discard the activity. Mirrors the
    // behaviour of the old recording path: no silent Garmin Connect litter.
    function finishWorkout() as Void {
        if (_exitPending) { return; }
        stopRest();
        _awaitingReps = false;
        if (_session != null and !_sessionStopped) {
            _session.stop();
            _sessionStopped = true;
        }
        var menu = new WatchUi.Menu2({ :title => "Finish workout" });
        menu.addItem(new WatchUi.MenuItem("Save & finish", null, "save", null));
        menu.addItem(new WatchUi.MenuItem("Discard workout", null, "discard", null));
        WatchUi.pushView(menu, new WorkoutFinishDelegate(self), WatchUi.SLIDE_UP);
    }

    // Popping the finish menu without choosing keeps the session open, so a
    // stray BACK cannot throw the workout away.
    function finishMenuDismissed() as Void {
        WatchUi.requestUpdate();
    }

    function resolveSave(save as Boolean) as Void {
        if (!_started) {
            // Already resolved once. The top button still re-opens the finish
            // menu while sitting on the DONE screen (pre-existing, not changed
            // here) - without this guard, choosing Save a second time would
            // re-POST the same workout and create a duplicate Liftosaur record.
            return;
        }
        // Whether the upload was actually dispatched: requestExit() below only
        // waits on the network when there is something in flight to wait for.
        var dispatched = false;
        if (save) {
            // Hand the finished workout to the backend, which writes it into
            // Liftosaur (updating the live record if one exists). Failures are
            // stashed and retried on the next launch.
            if (_comms != null) { dispatched = _comms.postWorkout(); }
        } else {
            // Discard deletes the live record - nothing left behind in
            // Liftosaur (decision #2). Fire-and-forget: never blocks the exit.
            if (_comms != null) { _comms.discardLive(); }
        }
        if (_session != null) {
            if (save) {
                writeSessionSummaryFields();
                _session.save();
                _activityNote = "saved to Garmin";
                System.println("Workout: SAVED " + _setsDone + "/" + _setsTotal + " sets");
            } else {
                _session.discard();
                _activityNote = "activity discarded";
            }
            _session = null;
        } else if (save) {
            _activityNote = "nothing to save";
        }
        stopSensorCapture();
        // NOTE: deliberately NOT resetting _exIndex/_setIndex here (deviation
        // from the plan's literal snippet - see PROGRESS.md Task 6 for why:
        // isFinished() is cursor-based, and zeroing the cursor would make the
        // DONE screen and the onBack() exit fix below both stop working the
        // instant Save/Discard is chosen). selectDay() already resets the
        // cursor and every editable field for any future workout attempt.
        // Freeze the elapsed time BEFORE _started/_startedAt are cleared below:
        // elapsedMs() reads !_started as "unknown" (0), so without this the
        // DONE screen's elapsedText() would drop from the real duration to
        // "0 min" the instant Save/Discard is chosen.
        _finalElapsedMs = elapsedMs();
        _awaitingReps = false;
        _repsEditing = false;
        _started = false;
        _startedAt = 0;
        _sessionStopped = false;
        clearSaved();
        clearPending();
        // Save waits (up to the watchdog) for the upload it just dispatched;
        // Discard - or a save with nothing to upload - has nothing to wait for.
        requestExit(save and dispatched);
    }

    private function stopSensorCapture() as Void {
        if (_hrTimer != null) {
            _hrTimer.stop();
            _hrTimer = null;
        }
        if (Toybox has :Sensor) {
            try { Sensor.unregisterSensorDataListener(); } catch (e) { }
        }
    }

    // ---- exit after finish (Task 1) ----

    // Called by the upload callback (success or failure) and by the watchdog.
    // Guarded on _exitPending so a background retry at app start (which also
    // goes through LiftComms.onPostResponse) can never close the app.
    function finishExit() as Void {
        if (!_exitPending) { return; }
        // Minimum dwell: the sync result is the whole point of the summary screen,
        // and Session.save() has just written the FIT file. Without this the app
        // can close ~0.3 s after Save when the upload is quick, so the user never
        // reads "synced to Liftosaur".
        var held = Time.now().value() - _exitRequestedAt;
        if (held < 2) {
            var waitMs = (2 - held) * 1000;
            if (waitMs < 250) { waitMs = 250; }
            var defer = new Timer.Timer();
            defer.start(method(:finishExit), waitMs, false);
            return;
        }
        _exitPending = false;
        if (_exitTimer != null) { _exitTimer.stop(); _exitTimer = null; }
        stopRest();
        stopSensorCapture();
        System.println("Workout: exiting after finish");
        System.exit();
    }

    function requestExit(waitForUpload as Boolean) as Void {
        if (_exitPending) { return; }
        _exitPending = true;
        _exitRequestedAt = Time.now().value();
        WatchUi.requestUpdate();
        if (!waitForUpload) {
            // Discard: nothing to read and nothing in flight - leave at once, so
            // the minimum-dwell above must not apply.
            _exitRequestedAt = Time.now().value() - 10;
            finishExit();
            return;
        }
        _exitTimer = new Timer.Timer();
        _exitTimer.start(method(:finishExit), 8000, false);
    }

    function exitPending() as Boolean { return _exitPending; }

    // Reported on the finish screen: the user could not tell whether the
    // activity reached Garmin Connect, so say so plainly.
    function activityNote() as String { return _activityNote; }
    function syncNote() as String { return _syncNote; }
    function setSyncNote(t as String) as Void { _syncNote = t; }
    function lapsAdded() as Number { return _lapsAdded; }

    // Wall-clock, not System.getTimer(): the timer counts from BOOT, so a session
    // restored after a restart used to report the device uptime as its duration
    // (a 45-minute workout was recorded as 27138s). Clamped so a bad clock can
    // never write an absurd number into the training record.
    function elapsedMs() as Number {
        if (!_started or _startedAt <= 0) { return 0; }
        var d = Time.now().value() - _startedAt;
        if (d < 0 or d > 21600) { return 0; }
        return d * 1000;
    }

    // ---- end-of-workout summary accessors (used once isFinished()) ----
    function dayTitle() as String { return dayLabel(_dayIndex); }
    function progressText() as String { return _setsDone + " of " + _setsTotal + " sets"; }
    function elapsedText() as String {
        var ms = (_finalElapsedMs >= 0) ? _finalElapsedMs : elapsedMs();
        var mins = (ms / 1000) / 60;
        return mins + " min";
    }
}

class WorkoutFinishDelegate extends WatchUi.Menu2InputDelegate {

    private var _c;

    function initialize(c as WorkoutController) {
        Menu2InputDelegate.initialize();
        _c = c;
    }

    function onSelect(item as WatchUi.MenuItem) as Void {
        _c.resolveSave(item.getId().equals("save"));
        WatchUi.popView(WatchUi.SLIDE_DOWN);
    }
}
