// Liftosaur watch workout — model + controller.
//
// The app works STANDALONE in the gym: the plan is baked in at build time
// (source/PlanData.mc, generated by tools/plan_from_liftosaur.py from the user's
// Liftosaur program), so there is no BLE and no network during a workout.
//
// Responsibilities:
//   - hold the workout cursor (day / exercise / set) and what has been logged
//   - persist that cursor so an accidental exit does not lose the session
//   - run the rest countdown between sets (with a vibrate)
//   - record a Garmin activity (strength training) for the session
//
// The BLE streaming experiment (LiftBleTransport / RecordingController /
// SampleBuffer) is deliberately NOT used here: it is parked, see docs/04.

import Toybox.Activity;
import Toybox.ActivityRecording;
import Toybox.Application;
import Toybox.Attention;
import Toybox.Lang;
import Toybox.System;
import Toybox.Timer;
import Toybox.WatchUi;

const STORE_KEY = "lift_workout_v1";

class WorkoutController {

    private var _days;          // Array of day dictionaries from LiftPlan
    private var _section;       // "Week 1" — the section the chosen day came from
    private var _dayIndex;      // index into _days
    private var _exIndex;
    private var _setIndex;
    private var _logged;        // Array of Arrays of Booleans
    private var _weights;       // Array of Arrays of Numbers (editable per set)
    private var _reps;          // Array of Arrays of Numbers
    private var _started;       // workout in progress
    private var _session;       // ActivityRecording.Session
    private var _sessionMs;

    private var _restRemaining;
    private var _restTotal;
    private var _restTimer;

    private var _setsDone;
    private var _setsTotal;
    private var _program;
    private var _pendingBody;
    private var _pendingSets;
    private var _comms;                 // set by the app; null in tests

    function initialize() {
        _days = LiftPlan.days();
        // Only the main (non-deload) section is offered for now; the deload
        // days are in the plan and can be switched on later.
        _section = "";
        for (var i = 0; i < _days.size(); i++) {
            var d = _days[i] as Dictionary;
            var sec = d[:section] as String;
            if (_section.equals("")) {
                _section = sec;
            }
        }
        _dayIndex = 0;
        _exIndex = 0;
        _setIndex = 0;
        _started = false;
        _session = null;
        _sessionMs = 0;
        _restRemaining = 0;
        _restTotal = 0;
        _restTimer = null;
        _logged = [];
        _weights = [];
        _reps = [];
        _setsDone = 0;
        _setsTotal = 0;
        _program = "";
        _pendingBody = null;
        _pendingSets = 0;
        _resetEditable();
    }

    // ------------------------------------------------------------- plan access

    // Days in the section being used (keeps deload days out of the picker).
    function dayCount() as Number {
        var n = 0;
        for (var i = 0; i < _days.size(); i++) {
            if (((_days[i] as Dictionary)[:section] as String).equals(_section)) {
                n++;
            }
        }
        return n;
    }

    private function dayAt(index as Number) as Dictionary or Null {
        var seen = 0;
        for (var i = 0; i < _days.size(); i++) {
            var d = _days[i] as Dictionary;
            if ((d[:section] as String).equals(_section)) {
                if (seen == index) { return d; }
                seen++;
            }
        }
        return null;
    }

    function section() as String { return _section; }

    function setProgram(name as String) as Void { _program = name; }

    function setComms(c as LiftComms) as Void { _comms = c; }

    // The day currently highlighted in the picker.
    function selectedDay() as Number { return _dayIndex; }

    function currentDay() as Dictionary or Null {
        return dayAt(_dayIndex);
    }

    function dayName(index as Number) as String {
        var d = dayAt(index);
        return d == null ? "-" : d[:name] as String;
    }

    function dayExerciseCount(index as Number) as Number {
        var d = dayAt(index);
        return d == null ? 0 : (d[:exercises] as Array).size();
    }

    function daySetCount(index as Number) as Number {
        var d = dayAt(index);
        if (d == null) { return 0; }
        var n = 0;
        var exs = d[:exercises] as Array;
        for (var i = 0; i < exs.size(); i++) {
            n += ((exs[i] as Dictionary)[:sets] as Array).size();
        }
        return n;
    }

    function currentExercises() as Array {
        var d = currentDay();
        return d == null ? [] : d[:exercises] as Array;
    }

    function currentExerciseIndex() as Number { return _exIndex; }

    function currentExerciseName() as String {
        var exs = currentExercises();
        if (_exIndex >= exs.size()) { return "done"; }
        return (exs[_exIndex] as Dictionary)[:name] as String;
    }

    function currentExerciseSetCount() as Number {
        var exs = currentExercises();
        if (_exIndex >= exs.size()) { return 0; }
        return ((exs[_exIndex] as Dictionary)[:sets] as Array).size();
    }

    function currentSetNumber() as Number { return _setIndex + 1; }

    function currentReps() as Number { return _reps[_exIndex][_setIndex]; }

    function currentWeight() as Number { return _weights[_exIndex][_setIndex]; }

    function currentRest() as Number {
        var exs = currentExercises();
        if (_exIndex >= exs.size()) { return 0; }
        return (exs[_exIndex] as Dictionary)[:rest] as Number;
    }

    function currentAmrap() as Boolean {
        var exs = currentExercises();
        if (_exIndex >= exs.size()) { return false; }
        var sets = (exs[_exIndex] as Dictionary)[:sets] as Array;
        if (_setIndex >= sets.size()) { return false; }
        return (sets[_setIndex] as Dictionary)[:amrap] as Boolean;
    }

    function isLogged(ex as Number, set as Number) as Boolean {
        if (ex >= _logged.size()) { return false; }
        if (set >= _logged[ex].size()) { return false; }
        return _logged[ex][set] as Boolean;
    }

    function isCurrentLogged() as Boolean { return isLogged(_exIndex, _setIndex); }

    function setsDone() as Number { return _setsDone; }
    function setsTotal() as Number { return _setsTotal; }
    function isStarted() as Boolean { return _started; }
    function isFinished() as Boolean { return _exIndex >= currentExercises().size(); }
    function setIndex() as Number { return _setIndex; }

    // ------------------------------------------------------------ session flow

    // Seed the editable copy of the plan so the user's weight edits stick.
    private function _resetEditable() as Void {
        _logged = [];
        _weights = [];
        _reps = [];
        _setsDone = 0;
        _setsTotal = 0;
        var exs = currentExercises();
        for (var i = 0; i < exs.size(); i++) {
            var sets = (exs[i] as Dictionary)[:sets] as Array;
            var lrow = [];
            var wrow = [];
            var rrow = [];
            for (var j = 0; j < sets.size(); j++) {
                var s = sets[j] as Dictionary;
                lrow.add(false);
                wrow.add(s[:weight] as Number);
                rrow.add(s[:reps] as Number);
                _setsTotal++;
            }
            _logged.add(lrow);
            _weights.add(wrow);
            _reps.add(rrow);
        }
    }

    function selectDay(index as Number) as Void {
        _dayIndex = index;
        _exIndex = 0;
        _setIndex = 0;
        _resetEditable();
        _restRemaining = 0;
        _restTotal = 0;
    }

    // Begin the session: start recording so Garmin Connect still gets an activity.
    function startWorkout() as Void {
        if (_started) { return; }
        _started = true;
        _sessionMs = System.getTimer();
        if (Toybox has :ActivityRecording) {
            _session = ActivityRecording.createSession({
                :name     => "Liftosaur " + dayName(_dayIndex),
                :sport    => Activity.SPORT_TRAINING,
                :subSport => Activity.SUB_SPORT_STRENGTH_TRAINING
            });
            _session.start();
        }
        save();
    }

    // Adjust the current set's weight by delta (5 lb steps in the UI).
    function adjustWeight(delta as Number) as Void {
        if (isFinished()) { return; }
        var w = _weights[_exIndex][_setIndex] as Number;
        var nw = w + delta;
        if (nw < 0) { nw = 0; }
        _weights[_exIndex][_setIndex] = nw;
    }

    function adjustReps(delta as Number) as Void {
        if (isFinished()) { return; }
        var r = _reps[_exIndex][_setIndex] as Number;
        var nr = r + delta;
        if (nr < 1) { nr = 1; }
        _reps[_exIndex][_setIndex] = nr;
    }

    // Mark the current set done and move on, starting the rest countdown.
    function completeSet() as Void {
        if (isFinished()) { return; }
        if (!isLogged(_exIndex, _setIndex)) {
            _logged[_exIndex][_setIndex] = true;
            _setsDone++;
        }
        var rest = currentRest();
        // advance within the exercise, then to the next exercise
        if (_setIndex + 1 < currentExerciseSetCount()) {
            _setIndex++;
        } else {
            _exIndex++;
            _setIndex = 0;
        }
        if (!isFinished() && rest > 0) {
            startRest(rest);
        }
        save();
        WatchUi.requestUpdate();
    }

    // Step back a set (mis-tap recovery).
    function previousSet() as Void {
        if (_setIndex > 0) {
            _setIndex--;
        } else if (_exIndex > 0) {
            _exIndex--;
            _setIndex = currentExerciseSetCount() - 1;
        }
        save();
        WatchUi.requestUpdate();
    }

    function skipExercise() as Void {
        if (isFinished()) { return; }
        _exIndex++;
        _setIndex = 0;
        save();
        WatchUi.requestUpdate();
    }

    // ------------------------------------------------------------------- rest

    function startRest(seconds as Number) as Void {
        _restTotal = seconds;
        _restRemaining = seconds;
        if (_restTimer == null) {
            _restTimer = new Timer.Timer();
        }
        _restTimer.stop();
        _restTimer.start(method(:onRestTick), 1000, true);
    }

    function onRestTick() as Void {
        if (_restRemaining > 0) {
            _restRemaining--;
        }
        if (_restRemaining == 0) {
            stopRest();
            if (Toybox has :Attention) {
                Attention.vibrate([new Attention.VibeProfile(100, 300)]);
            }
        }
        WatchUi.requestUpdate();
    }

    function stopRest() as Void {
        if (_restTimer != null) {
            _restTimer.stop();
        }
        _restRemaining = 0;
    }

    function restRemaining() as Number { return _restRemaining; }
    function restTotal() as Number { return _restTotal; }
    function isResting() as Boolean { return _restRemaining > 0; }

    // ----------------------------------------------------------- persistence

    // Storage accepts scalars and 1-D arrays, but not nested arrays, and its
    // generics are strict. Serialising to a String sidesteps both: "135,170,..."
    // for numbers and "0110..." for the logged flags.
    private function joinNumbers(grid as Array) as String {
        var out = "";
        var first = true;
        for (var i = 0; i < grid.size(); i++) {
            var row = grid[i] as Array;
            for (var j = 0; j < row.size(); j++) {
                if (!first) { out += ","; }
                out += (row[j] as Number).toString();
                first = false;
            }
        }
        return out;
    }

    private function joinBooleans(grid as Array) as String {
        var out = "";
        for (var i = 0; i < grid.size(); i++) {
            var row = grid[i] as Array;
            for (var j = 0; j < row.size(); j++) {
                out += ((row[j] as Boolean) ? "1" : "0");
            }
        }
        return out;
    }

    private function splitNumbers(str as String, grid as Array) as Void {
        if (str == null || str.equals("")) { return; }
        // String.split() is not available on this runtime, so tokenise by hand.
        var toks = [];
        var start = 0;
        var len = str.length();
        for (var i = 0; i <= len; i++) {
            var atEnd = (i == len);
            if (atEnd || (str.substring(i, i + 1) as String).equals(",")) {
                if (i > start) { toks.add(str.substring(start, i)); }
                start = i + 1;
            }
        }
        var k = 0;
        for (var gi = 0; gi < grid.size(); gi++) {
            var row = grid[gi] as Array;
            for (var gj = 0; gj < row.size(); gj++) {
                if (k < toks.size()) {
                    var v = (toks[k] as String).toNumber();
                    if (v != null) { row[gj] = v; }
                }
                k++;
            }
        }
    }

    private function splitBooleans(str as String, grid as Array) as Void {
        if (str == null || str.equals("")) { return; }
        var k = 0;
        for (var i = 0; i < grid.size(); i++) {
            var row = grid[i] as Array;
            for (var j = 0; j < row.size(); j++) {
                if (k < str.length()) {
                    row[j] = (str.substring(k, k + 1) as String).equals("1");
                }
                k++;
            }
        }
    }

    function save() as Void {
        Application.Storage.setValue("lift_day", _dayIndex);
        Application.Storage.setValue("lift_ex", _exIndex);
        Application.Storage.setValue("lift_set", _setIndex);
        Application.Storage.setValue("lift_started", _started);
        Application.Storage.setValue("lift_done", _setsDone);
        Application.Storage.setValue("lift_total", _setsTotal);
        Application.Storage.setValue("lift_weights", joinNumbers(_weights));
        Application.Storage.setValue("lift_reps", joinNumbers(_reps));
        Application.Storage.setValue("lift_logged", joinBooleans(_logged));
    }

    // Restore an interrupted session, if the plan still matches.
    function restore() as Boolean {
        var day = Application.Storage.getValue("lift_day");
        if (day == null) { return false; }
        var d = day as Number;
        if (d >= dayCount()) { return false; }
        _dayIndex = d;
        _exIndex = Application.Storage.getValue("lift_ex") as Number;
        _setIndex = Application.Storage.getValue("lift_set") as Number;
        _started = Application.Storage.getValue("lift_started") as Boolean;
        _setsDone = Application.Storage.getValue("lift_done") as Number;
        _setsTotal = Application.Storage.getValue("lift_total") as Number;
        var w = Application.Storage.getValue("lift_weights");
        if (w != null) { splitNumbers(w as String, _weights); }
        var r = Application.Storage.getValue("lift_reps");
        if (r != null) { splitNumbers(r as String, _reps); }
        var l = Application.Storage.getValue("lift_logged");
        if (l != null) { splitBooleans(l as String, _logged); }
        return true;
    }

    function clearSaved() as Void {
        Application.Storage.deleteValue("lift_day");
        Application.Storage.deleteValue("lift_ex");
        Application.Storage.deleteValue("lift_set");
        Application.Storage.deleteValue("lift_started");
        Application.Storage.deleteValue("lift_done");
        Application.Storage.deleteValue("lift_total");
        Application.Storage.deleteValue("lift_weights");
        Application.Storage.deleteValue("lift_reps");
        Application.Storage.deleteValue("lift_logged");
    }

    // ------------------------------------------------------------ backend sync

    // Swap in the plan fetched from the backend. Refused once a workout is
    // under way: replacing the plan mid-session would invalidate the cursor.
    function adoptRemotePlan(days as Array) as Boolean {
        if (_started or days.size() == 0) { return false; }
        _days = days;
        _section = "";
        for (var i = 0; i < _days.size(); i++) {
            var sec = (_days[i] as Dictionary)[:section] as String;
            if (_section.equals("")) { _section = sec; }
        }
        _dayIndex = 0;
        _exIndex = 0;
        _setIndex = 0;
        _resetEditable();
        return true;
    }

    // The body for POST /api/v1/watch/workout: only sets the user actually
    // completed, in the order they were trained.
    function buildWorkoutBody() as Dictionary or Null {
        var sets = [];
        var exs = currentExercises();
        for (var i = 0; i < exs.size(); i++) {
            var name = (exs[i] as Dictionary)[:name] as String;
            var planSets = (exs[i] as Dictionary)[:sets] as Array;
            for (var j = 0; j < planSets.size(); j++) {
                if (!isLogged(i, j)) { continue; }
                sets.add({
                    :exercise => name,
                    :weight => _weights[i][j] as Number,
                    :reps => _reps[i][j] as Number,
                    :amrap => (planSets[j] as Dictionary)[:amrap] as Boolean
                });
            }
        }
        if (sets.size() == 0) { return null; }
        return {
            :day => dayName(_dayIndex),
            :section => _section,
            :program => _program,
            :week => 1,
            :day_in_week => _dayIndex + 1,
            :duration_s => elapsedMs() / 1000,
            :sets => sets
        };
    }

    // Compact stash for a workout that could not be uploaded:
    // "day|section|program|duration;Ex|w|r|a;Ex|w|r|a"
    function pendingText() as String or Null {
        var body = buildWorkoutBody();
        if (body == null) { return null; }
        var out = (body[:day] as String) + "|" + (body[:section] as String) + "|" +
                  (body[:program] as String) + "|" + (body[:duration_s] as Number);
        var sets = body[:sets] as Array;
        for (var i = 0; i < sets.size(); i++) {
            var s = sets[i] as Dictionary;
            out += ";" + (s[:exercise] as String) + "|" + (s[:weight] as Number) + "|" +
                   (s[:reps] as Number) + "|" + ((s[:amrap] as Boolean) ? "1" : "0");
        }
        return out;
    }

    // Rebuild a stashed workout so it can be posted again.
    function loadPendingText(text as String) as Boolean {
        var i = text.find(";");
        if (i == null) { return false; }
        var head = text.substring(0, i);
        var fields = _split(head, "|");
        if (fields.size() < 4) { return false; }
        var sets = [];
        var rest = text.substring(i + 1, text.length());
        var parts = _split(rest, ";");
        for (var k = 0; k < parts.size(); k++) {
            var f = _split(parts[k] as String, "|");
            if (f.size() < 4) { continue; }
            sets.add({:exercise => f[0], :weight => (f[1] as String).toNumber(),
                      :reps => (f[2] as String).toNumber(),
                      :amrap => (f[3] as String).equals("1")});
        }
        if (sets.size() == 0) { return false; }
        _pendingBody = {
            :day => fields[0], :section => fields[1], :program => fields[2],
            :duration_s => (fields[3] as String).toNumber(),
            :week => 1, :day_in_week => 1, :sets => sets
        };
        _pendingSets = sets.size();
        return true;
    }

    function buildWorkoutBodyOrPending() as Dictionary or Null {
        if (_pendingBody != null) { return _pendingBody; }
        return buildWorkoutBody();
    }

    function pendingSetCount() as Number { return _pendingSets; }

    private function _split(s as String, sep as String) as Array {
        var out = [];
        var start = 0;
        var len = s.length();
        for (var i = 0; i <= len; i++) {
            var atEnd = (i == len);
            if (atEnd or (s.substring(i, i + 1) as String).equals(sep)) {
                out.add(s.substring(start, i));
                start = i + 1;
            }
        }
        return out;
    }

    // ------------------------------------------------------------------ finish

    // Stop recording and let the user keep or discard the activity. Mirrors the
    // behaviour of the old recording path: no silent Garmin Connect litter.
    function finishWorkout() as Void {
        stopRest();
        if (_session != null) {
            _session.stop();
        }
        WatchUi.pushView(new WatchUi.Confirmation("Save workout?"),
                         new WorkoutSaveDelegate(self), WatchUi.SLIDE_UP);
    }

    function resolveSave(save as Boolean) as Void {
        if (save) {
            // Hand the finished workout to the backend, which writes it into
            // Liftosaur. Failures are stashed and retried on the next launch.
            if (_comms != null) { _comms.postWorkout(); }
        }
        if (_session != null) {
            if (save) {
                _session.save();
                System.println("Workout: SAVED " + _setsDone + "/" + _setsTotal + " sets");
            } else {
                _session.discard();
                System.println("Workout: DISCARDED");
            }
            _session = null;
        }
        _started = false;
        clearSaved();
    }

    function elapsedMs() as Number {
        return _started ? (System.getTimer() - _sessionMs) : 0;
    }
}

class WorkoutSaveDelegate extends WatchUi.ConfirmationDelegate {

    private var _c;

    function initialize(c as WorkoutController) {
        WatchUi.ConfirmationDelegate.initialize();
        _c = c;
    }

    function onResponse(response as WatchUi.Confirm) as Boolean {
        _c.resolveSave(response == WatchUi.CONFIRM_YES);
        return true;
    }
}
