// Liftosaur watch workout — model + controller.
//
// The app works STANDALONE in the gym: the plan is baked in at build time
// (source/PlanData.mc, generated by tools/plan_from_liftosaur.py from the user's
// Liftosaur program), so there is no BLE and no network during a workout.
//
// Responsibilities:
//   - hold the workout cursor (day / exercise / set) and what has been logged
//   - persist that cursor so an accidental exit does not lose the session
//   - run the rest countdown between sets (with a vibrate)
//   - record a Garmin activity (strength training) for the session
//
// The BLE streaming experiment (LiftBleTransport / RecordingController /
// SampleBuffer) is deliberately NOT used here: it is parked, see docs/04.

import Toybox.Activity;
import Toybox.ActivityRecording;
import Toybox.Application;
import Toybox.Attention;
import Toybox.Lang;
import Toybox.System;
import Toybox.Timer;
import Toybox.WatchUi;

const STORE_KEY = "lift_workout_v1";

class WorkoutController {

    private var _days;          // Array of day dictionaries from LiftPlan
    private var _section;       // "Week 1" — the section the chosen day came from
    private var _dayIndex;      // index into _days
    private var _exIndex;
    private var _setIndex;
    private var _logged;        // Array of Arrays of Booleans
    private var _weights;       // Array of Arrays of Numbers (editable per set)
    private var _reps;          // Array of Arrays of Numbers
    private var _started;       // workout in progress
    private var _session;       // ActivityRecording.Session
    private var _sessionMs;

    private var _restRemaining;
    private var _restTotal;
    private var _restTimer;

    private var _setsDone;
    private var _setsTotal;
    private var _program;
    private var _pendingBody;
    private var _pendingSets;
    private var _comms;                 // set by the app; null in tests
    private var _programs;              // Array of program dicts from the backend
    private var _programIndex;
    private var _programId;
    private var _awaitingReps;          // the AMRAP "how many did you get?" step
    private var _repsEditing;
    private var _activityNote;          // what happened to the Garmin activity
    private var _syncNote;              // what happened to the Liftosaur upload
    private var _lapsAdded;
    private var _sessionStopped;
    private var _info;                  // last fetched exercise history

    function initialize() {
        _days = LiftPlan.days();
        // Only the main (non-deload) section is offered for now; the deload
        // days are in the plan and can be switched on later.
        _section = "";
        for (var i = 0; i < _days.size(); i++) {
            var d = _days[i] as Dictionary;
            var sec = d[:section] as String;
            if (_section.equals("")) {
                _section = sec;
            }
        }
        _dayIndex = 0;
        _exIndex = 0;
        _setIndex = 0;
        _started = false;
        _session = null;
        _sessionMs = 0;
        _restRemaining = 0;
        _restTotal = 0;
        _restTimer = null;
        _logged = [];
        _weights = [];
        _reps = [];
        _setsDone = 0;
        _setsTotal = 0;
        _program = "";
        _pendingBody = null;
        _pendingSets = 0;
        _programs = [];
        _programIndex = 0;
        _programId = "";
        _awaitingReps = false;
        _repsEditing = false;
        _activityNote = "";
        _syncNote = "";
        _lapsAdded = 0;
        _info = null;
        _sessionStopped = false;
        _resetEditable();
    }

    // ------------------------------------------------------------- plan access

    // EVERY day in the plan: all week-blocks, deload included. The picker
    // distinguishes them by section label rather than hiding any.
    function dayCount() as Number { return _days.size(); }

    private function dayAt(index as Number) as Dictionary or Null {
        if (index < 0 or index >= _days.size()) { return null; }
        return _days[index] as Dictionary;
    }

    function section() as String { return _section; }

    function setProgram(name as String) as Void { _program = name; }

    function setComms(c as LiftComms) as Void { _comms = c; }

    // The day currently highlighted in the picker.
    function selectedDay() as Number { return _dayIndex; }

    function daySectionLabel(index as Number) as String {
        var d = dayAt(index);
        return d == null ? "" : d[:section] as String;
    }

    function hasChosenProgram() as Boolean {
        return Application.Storage.getValue("lift_program_id") != null;
    }

    function currentDay() as Dictionary or Null {
        return dayAt(_dayIndex);
    }

    function dayName(index as Number) as String {
        var d = dayAt(index);
        return d == null ? "-" : d[:name] as String;
    }

    // "Day 1" alone is ambiguous across week-blocks, so the picker shows the
    // section too: "Week 4 - Deload · Day 1".
    function dayLabel(index as Number) as String {
        var d = dayAt(index);
        if (d == null) { return "-"; }
        var sec = d[:section] as String;
        if (sec.equals("")) { return d[:name] as String; }
        return sec + " - " + (d[:name] as String);
    }

    // Every day in the plan, not just the first week-block.
    function allDays() as Boolean { return true; }

    function dayExerciseCount(index as Number) as Number {
        var d = dayAt(index);
        return d == null ? 0 : (d[:exercises] as Array).size();
    }

    function daySetCount(index as Number) as Number {
        var d = dayAt(index);
        if (d == null) { return 0; }
        var n = 0;
        var exs = d[:exercises] as Array;
        for (var i = 0; i < exs.size(); i++) {
            n += ((exs[i] as Dictionary)[:sets] as Array).size();
        }
        return n;
    }

    function currentExercises() as Array {
        var d = currentDay();
        return d == null ? [] : d[:exercises] as Array;
    }

    function currentExerciseIndex() as Number { return _exIndex; }

    function currentExerciseName() as String {
        var exs = currentExercises();
        if (_exIndex >= exs.size()) { return "done"; }
        return (exs[_exIndex] as Dictionary)[:name] as String;
    }

    function currentExerciseSetCount() as Number {
        var exs = currentExercises();
        if (_exIndex >= exs.size()) { return 0; }
        return ((exs[_exIndex] as Dictionary)[:sets] as Array).size();
    }

    function currentSetNumber() as Number { return _setIndex + 1; }

    // Bounds-safe: these are reachable from the info/menu screens, which can be
    // opened when the workout is finished and _exIndex is past the last exercise.
    function currentReps() as Number {
        if (_exIndex >= _reps.size() or _setIndex >= _reps[_exIndex].size()) { return 0; }
        return _reps[_exIndex][_setIndex];
    }

    function currentWeight() as Number {
        if (_exIndex >= _weights.size() or _setIndex >= _weights[_exIndex].size()) { return 0; }
        return _weights[_exIndex][_setIndex];
    }

    function currentRest() as Number {
        var exs = currentExercises();
        if (_exIndex >= exs.size()) { return 0; }
        return (exs[_exIndex] as Dictionary)[:rest] as Number;
    }

    function currentAmrap() as Boolean {
        var exs = currentExercises();
        if (_exIndex >= exs.size()) { return false; }
        if (_setIndex >= ((exs[_exIndex] as Dictionary)[:sets] as Array).size()) { return false; }
        if (_exIndex >= exs.size()) { return false; }
        var sets = (exs[_exIndex] as Dictionary)[:sets] as Array;
        if (_setIndex >= sets.size()) { return false; }
        return (sets[_setIndex] as Dictionary)[:amrap] as Boolean;
    }

    function isLogged(ex as Number, set as Number) as Boolean {
        if (ex >= _logged.size()) { return false; }
        if (set >= _logged[ex].size()) { return false; }
        return _logged[ex][set] as Boolean;
    }

    function isCurrentLogged() as Boolean { return isLogged(_exIndex, _setIndex); }

    function setsDone() as Number { return _setsDone; }
    function setsTotal() as Number { return _setsTotal; }
    function isStarted() as Boolean { return _started; }
    function isFinished() as Boolean { return _exIndex >= currentExercises().size(); }
    function setIndex() as Number { return _setIndex; }

    // ------------------------------------------------------------ session flow

    // Seed the editable copy of the plan so the user's weight edits stick.
    private function _resetEditable() as Void {
        _logged = [];
        _weights = [];
        _reps = [];
        _setsDone = 0;
        _setsTotal = 0;
        var exs = currentExercises();
        for (var i = 0; i < exs.size(); i++) {
            var sets = (exs[i] as Dictionary)[:sets] as Array;
            var lrow = [];
            var wrow = [];
            var rrow = [];
            for (var j = 0; j < sets.size(); j++) {
                var s = sets[j] as Dictionary;
                lrow.add(false);
                wrow.add(s[:weight] as Number);
                rrow.add(s[:reps] as Number);
                _setsTotal++;
            }
            _logged.add(lrow);
            _weights.add(wrow);
            _reps.add(rrow);
        }
    }

    function selectDay(index as Number) as Void {
        _dayIndex = index;
        _exIndex = 0;
        _setIndex = 0;
        _resetEditable();
        _restRemaining = 0;
        _restTotal = 0;
        _awaitingReps = false;
    }

    // Begin the session: start recording so Garmin Connect still gets an activity.
    function startWorkout() as Void {
        if (_started) { return; }
        _started = true;
        _sessionMs = System.getTimer();
        _lapsAdded = 0;
        if (Toybox has :ActivityRecording) {
            _session = ActivityRecording.createSession({
                :name     => "Liftosaur - " + dayName(_dayIndex),
                :sport    => Activity.SPORT_TRAINING,
                :subSport => Activity.SUB_SPORT_STRENGTH_TRAINING
            });
            if (_session == null) {
                _activityNote = "activity not started";
            } else {
                _session.start();
                _sessionStopped = false;
                _activityNote = "";
            }
        } else {
            _activityNote = "recording unsupported";
        }
        save();
    }

    // Adjust the current set's weight by delta (5 lb steps in the UI).
    function adjustWeight(delta as Number) as Void {
        if (isFinished()) { return; }
        var w = _weights[_exIndex][_setIndex] as Number;
        var nw = w + delta;
        if (nw < 0) { nw = 0; }
        _weights[_exIndex][_setIndex] = nw;
    }

    function adjustReps(delta as Number) as Void {
        if (isFinished()) { return; }
        var r = _reps[_exIndex][_setIndex] as Number;
        var nr = r + delta;
        if (nr < 1) { nr = 1; }
        _reps[_exIndex][_setIndex] = nr;
    }

    // SELECT during rest must ONLY end the rest. Previously it fell through to
    // completeSet(), which logged a set that had not happened yet and started a
    // fresh rest - so "skipping" silently ate the next set.
    function skipRest() as Void {
        stopRest();
        WatchUi.requestUpdate();
    }

    // The AMRAP set drives 5/3/1 progression, so its ACTUAL reps matter. Rather
    // than log the target, the app asks: adjust with a swipe, confirm with
    // SELECT. Only gestures proven to work on this device are used.
    function isAwaitingReps() as Boolean { return _awaitingReps; }

    function beginRepsEntry() as Void {
        _awaitingReps = true;
        WatchUi.requestUpdate();
    }

    // Confirm the reps just entered and finally log the set.
    function confirmReps() as Void {
        if (!_awaitingReps) { return; }
        _awaitingReps = false;
        completeSet();
    }

    // The only structured marker this device supports: addSets()/SetType do not
    // exist on the Venu 2S (verified against its API file), so each completed set
    // becomes a LAP. That at least gives the activity real content and per-set
    // timing in Garmin Connect.
    private function markLap() as Void {
        if (_session == null) { return; }
        _session.addLap();
        _lapsAdded++;
    }

    // Mark the current set done and move on, starting the rest countdown.
    function completeSet() as Void {
        if (isFinished()) { return; }
        // An AMRAP set asks for its actual reps first (unless we are confirming).
        if (currentAmrap() and !isLogged(_exIndex, _setIndex) and !_awaitingReps) {
            beginRepsEntry();
            return;
        }
        _awaitingReps = false;
        if (!isLogged(_exIndex, _setIndex)) {
            _logged[_exIndex][_setIndex] = true;
            _setsDone++;
            markLap();
        }
        var rest = currentRest();
        // advance within the exercise, then to the next exercise
        if (_setIndex + 1 < currentExerciseSetCount()) {
            _setIndex++;
        } else {
            _exIndex++;
            _setIndex = 0;
        }
        if (!isFinished() && rest > 0) {
            startRest(rest);
        }
        save();
        WatchUi.requestUpdate();
    }

    // Step back a set (mis-tap recovery).
    function previousSet() as Void {
        if (_setIndex > 0) {
            _setIndex--;
        } else if (_exIndex > 0) {
            _exIndex--;
            _setIndex = currentExerciseSetCount() - 1;
        }
        save();
        WatchUi.requestUpdate();
    }

    // BACK / menu navigation. Stepping back un-logs the set so it can be redone;
    // stepping forward via the menu skips WITHOUT logging (the user may have
    // switched exercises), which completeSet() deliberately does not do.
    // ---- the exercise list (options -> View workout) ----
    function exerciseNameAt(index as Number) as String {
        var exs = currentExercises();
        if (index < 0 or index >= exs.size()) { return "-"; }
        return (exs[index] as Dictionary)[:name] as String;
    }

    function exerciseIsDone(index as Number) as Boolean {
        var exs = currentExercises();
        if (index < 0 or index >= exs.size()) { return false; }
        var sets = (exs[index] as Dictionary)[:sets] as Array;
        for (var j = 0; j < sets.size(); j++) {
            if (!isLogged(index, j)) { return false; }
        }
        return sets.size() > 0;
    }

    function jumpToExercise(index as Number) as Void {
        if (index < 0 or index >= currentExercises().size()) { return; }
        _exIndex = index;
        _setIndex = 0;
        _awaitingReps = false;
        save();
        WatchUi.requestUpdate();
    }

    // Every SET of the day, flattened, so the list can be per-set rather than
    // per-exercise: "Squat 220 x 5" is what you actually need to find.
    function setCount() as Number {
        var n = 0;
        var exs = currentExercises();
        for (var i = 0; i < exs.size(); i++) {
            n += ((exs[i] as Dictionary)[:sets] as Array).size();
        }
        return n;
    }

    // Flat index over every set: [exercise index, set index]
    private function setRefAt(flat as Number) as Array {
        var exs = currentExercises();
        var k = 0;
        for (var i = 0; i < exs.size(); i++) {
            var sn = ((exs[i] as Dictionary)[:sets] as Array).size();
            if (flat < k + sn) { return [i, flat - k]; }
            k += sn;
        }
        return [0, 0];
    }

    function setLabelAt(flat as Number) as String {
        var ref = setRefAt(flat);
        var ei = ref[0] as Number;
        var si = ref[1] as Number;
        var exs = currentExercises();
        if (ei >= exs.size()) { return "-"; }
        var name = (exs[ei] as Dictionary)[:name] as String;
        var reps = _reps[ei][si] as Number;
        var amrap = (((exs[ei] as Dictionary)[:sets] as Array)[si] as Dictionary)[:amrap] as Boolean;
        return name + "  " + (_weights[ei][si] as Number) + " x " + reps +
               (amrap ? "+" : "");
    }

    function setSublabelAt(flat as Number) as String {
        var ref = setRefAt(flat);
        var ei = ref[0] as Number;
        var si = ref[1] as Number;
        var exs = currentExercises();
        var sn = ((exs[ei] as Dictionary)[:sets] as Array).size();
        var mark = isLogged(ei, si) ? "done" : "todo";
        if (ei == _exIndex and si == _setIndex) { mark += "  now"; }
        return "set " + (si + 1) + " of " + sn + "   " + mark;
    }

    function jumpToSet(flat as Number) as Void {
        var ref = setRefAt(flat);
        _exIndex = ref[0] as Number;
        _setIndex = ref[1] as Number;
        _awaitingReps = false;
        save();
        WatchUi.requestUpdate();
    }

    // ---- exercise info (previous session, from the backend) ----
    function setExerciseInfo(dict as Dictionary or Null) as Void { _info = dict; }

    function infoLoaded() as Boolean { return _info != null; }

    // "5x120  3x140  1x155" — grouped, because that is how it scrolls by
    function infoSetsText() as String {
        if (_info == null) { return ""; }
        var last = _info["last"];
        if (!(last instanceof Dictionary)) { return "no previous session"; }
        var sets = (last as Dictionary)["sets"];
        if (!(sets instanceof Array)) { return ""; }
        var out = "";
        var prevW = -1;
        var prevR = -1;
        var run = 0;
        for (var i = 0; i <= (sets as Array).size(); i++) {
            var w = -1;
            var r = -1;
            if (i < (sets as Array).size()) {
                var st = (sets as Array)[i] as Dictionary;
                w = st["weight"] as Number;
                r = st["reps"] as Number;
            }
            if (w == prevW and r == prevR) {
                run++;
            } else {
                if (run > 0) {
                    if (out.length() > 0) { out += "   "; }
                    out += run + "x" + prevR + " @ " + prevW;
                }
                prevW = w; prevR = r; run = 1;
            }
        }
        return out;
    }

    // Up to three short lines of "3x10 @ 95" groups. Built here, not in the
    // view: String.find(value, startIndex) does not exist on this device and
    // calling it threw "Too Many Arguments Error" inside onUpdate.
    function infoSetLines() as Array {
        var lines = [];
        if (_info == null) { return lines; }
        var last = _info["last"];
        if (!(last instanceof Dictionary)) { return lines; }
        var sets = (last as Dictionary)["sets"];
        if (!(sets instanceof Array)) { return lines; }
        var cur = "";
        var prevW = -1;
        var prevR = -1;
        var run = 0;
        for (var i = 0; i <= (sets as Array).size(); i++) {
            var w = -1;
            var r = -1;
            if (i < (sets as Array).size()) {
                var st = (sets as Array)[i] as Dictionary;
                w = st["weight"] as Number;
                r = st["reps"] as Number;
            }
            if (w == prevW and r == prevR) {
                run++;
            } else {
                if (run > 0) {
                    var grp = run + "x" + prevR + " @ " + prevW;
                    if ((cur.length() + grp.length() + 3) > 20) {
                        if (!cur.equals("")) { lines.add(cur); }
                        cur = grp;
                    } else {
                        cur = cur.equals("") ? grp : cur + "   " + grp;
                    }
                }
                prevW = w; prevR = r; run = 1;
            }
        }
        if (!cur.equals("")) { lines.add(cur); }
        return lines;
    }

    function infoDateText() as String {
        if (_info == null) { return ""; }
        var last = _info["last"];
        if (!(last instanceof Dictionary)) { return ""; }
        var d = (last as Dictionary)["date"];
        if (!(d instanceof String)) { return ""; }
        var s = d as String;
        if (s.length() > 10) { return s.substring(0, 10); }
        return s;
    }

    function infoTopText() as String {
        if (_info == null) { return ""; }
        var last = _info["last"];
        if (!(last instanceof Dictionary)) { return ""; }
        return "top " + ((last as Dictionary)["top_weight"] as Number) + " lb";
    }

    function infoVolumeText() as String {
        if (_info == null) { return ""; }
        var last = _info["last"];
        if (!(last instanceof Dictionary)) { return ""; }
        var sets = (last as Dictionary)["sets"];
        if (!(sets instanceof Array)) { return ""; }
        var vol = 0;
        for (var i = 0; i < (sets as Array).size(); i++) {
            var st = (sets as Array)[i] as Dictionary;
            vol += (st["weight"] as Number) * (st["reps"] as Number);
        }
        return "volume " + vol + " lb";
    }

    function infoE1rmText() as String {
        if (_info == null) { return ""; }
        var last = _info["last"];
        if (!(last instanceof Dictionary)) { return ""; }
        return "e1rm " + ((last as Dictionary)["e1rm"] as Number) + " lb";
    }

    // What the plan prescribes right now, for the info screen.
    function targetText() as String {
        if (isFinished()) { return "session complete"; }
        return currentWeight() + " lb x " + currentReps() +
               (currentAmrap() ? "+" : "") + "   rest " + currentRest() + "s";
    }

    // Session progress as a fraction, for the ring.
    function setProgress() as Float {
        var total = _setsTotal;
        return total <= 0 ? 0.0 : _setsDone.toFloat() / total.toFloat();
    }

    // The reps the PROGRAM prescribed for this set (what _reps started as), so
    // the adjust screen can show "target 5+" next to the edited value.
    function plannedReps() as Number {
        var exs = currentExercises();
        if (_exIndex >= exs.size()) { return 0; }
        var sets = (exs[_exIndex] as Dictionary)[:sets] as Array;
        if (_setIndex >= sets.size()) { return 0; }
        return (sets[_setIndex] as Dictionary)[:reps] as Number;
    }

    // Ask the backend for this exercise's previous session (info screen).
    function requestExerciseInfo() as Void {
        if (_comms != null) { _comms.fetchExerciseInfo(currentExerciseName()); }
    }

    // The compact payload to POST (live session, or a stashed retry).
    function outgoingPayload() as String or Null { return pendingText(); }

    // "Next set": logs the current set if it has not been logged yet (the
    // natural meaning of done-and-on), otherwise just advances.
    function advance() as Void {
        if (isFinished()) { finishWorkout(); return; }
        if (isLogged(_exIndex, _setIndex)) { stepForward(); }
        else { completeSet(); }
    }

    // Which field the edit screen's swipes are changing.
    function adjustFieldIsWeight() as Boolean { return !_repsEditing; }
    function toggleAdjustField() as Void { _repsEditing = !_repsEditing; }

    function canGoBack() as Boolean {
        return (_setIndex > 0) or (_exIndex > 0);
    }

    function stepForward() as Void {
        if (isFinished()) { return; }
        _awaitingReps = false;
        if (_setIndex + 1 < currentExerciseSetCount()) {
            _setIndex++;
        } else {
            _exIndex++;
            _setIndex = 0;
        }
        save();
        WatchUi.requestUpdate();
    }

    function skipExercise() as Void {
        if (isFinished()) { return; }
        _exIndex++;
        _setIndex = 0;
        save();
        WatchUi.requestUpdate();
    }

    // ------------------------------------------------------------------- rest

    function startRest(seconds as Number) as Void {
        // The user can add/remove rest with a swipe, so clamp at zero.
        if (seconds <= 0) {
            stopRest();
            WatchUi.requestUpdate();
            return;
        }
        _restTotal = seconds;
        _restRemaining = seconds;
        if (_restTimer == null) {
            _restTimer = new Timer.Timer();
        }
        _restTimer.stop();
        _restTimer.start(method(:onRestTick), 1000, true);
    }

    function onRestTick() as Void {
        if (_restRemaining > 0) {
            _restRemaining--;
        }
        if (_restRemaining == 0) {
            stopRest();
            if (Toybox has :Attention) {
                Attention.vibrate([new Attention.VibeProfile(100, 300)]);
            }
        }
        WatchUi.requestUpdate();
    }

    function stopRest() as Void {
        if (_restTimer != null) {
            _restTimer.stop();
        }
        _restRemaining = 0;
    }

    function restRemaining() as Number { return _restRemaining; }
    function restTotal() as Number { return _restTotal; }
    function isResting() as Boolean { return _restRemaining > 0; }

    // ----------------------------------------------------------- persistence

    // Storage accepts scalars and 1-D arrays, but not nested arrays, and its
    // generics are strict. Serialising to a String sidesteps both: "135,170,..."
    // for numbers and "0110..." for the logged flags.
    private function joinNumbers(grid as Array) as String {
        var out = "";
        var first = true;
        for (var i = 0; i < grid.size(); i++) {
            var row = grid[i] as Array;
            for (var j = 0; j < row.size(); j++) {
                if (!first) { out += ","; }
                out += (row[j] as Number).toString();
                first = false;
            }
        }
        return out;
    }

    private function joinBooleans(grid as Array) as String {
        var out = "";
        for (var i = 0; i < grid.size(); i++) {
            var row = grid[i] as Array;
            for (var j = 0; j < row.size(); j++) {
                out += ((row[j] as Boolean) ? "1" : "0");
            }
        }
        return out;
    }

    private function splitNumbers(str as String, grid as Array) as Void {
        if (str == null || str.equals("")) { return; }
        // String.split() is not available on this runtime, so tokenise by hand.
        var toks = [];
        var start = 0;
        var len = str.length();
        for (var i = 0; i <= len; i++) {
            var atEnd = (i == len);
            if (atEnd || (str.substring(i, i + 1) as String).equals(",")) {
                if (i > start) { toks.add(str.substring(start, i)); }
                start = i + 1;
            }
        }
        var k = 0;
        for (var gi = 0; gi < grid.size(); gi++) {
            var row = grid[gi] as Array;
            for (var gj = 0; gj < row.size(); gj++) {
                if (k < toks.size()) {
                    var v = (toks[k] as String).toNumber();
                    if (v != null) { row[gj] = v; }
                }
                k++;
            }
        }
    }

    private function splitBooleans(str as String, grid as Array) as Void {
        if (str == null || str.equals("")) { return; }
        var k = 0;
        for (var i = 0; i < grid.size(); i++) {
            var row = grid[i] as Array;
            for (var j = 0; j < row.size(); j++) {
                if (k < str.length()) {
                    row[j] = (str.substring(k, k + 1) as String).equals("1");
                }
                k++;
            }
        }
    }

    function save() as Void {
        Application.Storage.setValue("lift_day", _dayIndex);
        Application.Storage.setValue("lift_ex", _exIndex);
        Application.Storage.setValue("lift_set", _setIndex);
        Application.Storage.setValue("lift_started", _started);
        Application.Storage.setValue("lift_done", _setsDone);
        Application.Storage.setValue("lift_total", _setsTotal);
        Application.Storage.setValue("lift_weights", joinNumbers(_weights));
        Application.Storage.setValue("lift_reps", joinNumbers(_reps));
        Application.Storage.setValue("lift_logged", joinBooleans(_logged));
    }

    // Restore an interrupted session, if the plan still matches.
    function restore() as Boolean {
        var pid = Application.Storage.getValue("lift_program_id");
        if (pid != null) { _programId = pid as String; }
        var day = Application.Storage.getValue("lift_day");
        if (day == null) { return false; }
        var d = day as Number;
        if (d >= dayCount()) { return false; }
        _dayIndex = d;
        _exIndex = Application.Storage.getValue("lift_ex") as Number;
        _setIndex = Application.Storage.getValue("lift_set") as Number;
        _started = Application.Storage.getValue("lift_started") as Boolean;
        _setsDone = Application.Storage.getValue("lift_done") as Number;
        _setsTotal = Application.Storage.getValue("lift_total") as Number;
        var w = Application.Storage.getValue("lift_weights");
        if (w != null) { splitNumbers(w as String, _weights); }
        var r = Application.Storage.getValue("lift_reps");
        if (r != null) { splitNumbers(r as String, _reps); }
        var l = Application.Storage.getValue("lift_logged");
        if (l != null) { splitBooleans(l as String, _logged); }
        return true;
    }

    function clearSaved() as Void {
        Application.Storage.deleteValue("lift_day");
        Application.Storage.deleteValue("lift_ex");
        Application.Storage.deleteValue("lift_set");
        Application.Storage.deleteValue("lift_started");
        Application.Storage.deleteValue("lift_done");
        Application.Storage.deleteValue("lift_total");
        Application.Storage.deleteValue("lift_weights");
        Application.Storage.deleteValue("lift_reps");
        Application.Storage.deleteValue("lift_logged");
    }

    // ---------------------------------------------------------- program choice

    // Programs come from the backend as JSON dicts (string keys): id, name,
    // isCurrent. The chosen one is persisted so a restart keeps the selection.
    function setPrograms(list as Array) as Void {
        _programs = list;
        _programIndex = 0;
        for (var i = 0; i < _programs.size(); i++) {
            var p = _programs[i] as Dictionary;
            var cur = p["isCurrent"];
            if (cur instanceof Boolean and (cur as Boolean)) {
                _programIndex = i;
                break;
            }
        }
    }

    function programCount() as Number { return _programs.size(); }

    function programLabel(index as Number) as String {
        if (index < 0 or index >= _programs.size()) { return "-"; }
        var p = _programs[index] as Dictionary;
        var name = p["name"] as String;
        var cur = p["isCurrent"];
        if (cur instanceof Boolean and (cur as Boolean)) {
            return name + " (current)";
        }
        return name;
    }

    function programIdAt(index as Number) as String {
        if (index < 0 or index >= _programs.size()) { return "current"; }
        return (_programs[index] as Dictionary)["id"] as String;
    }

    function selectedProgramIndex() as Number { return _programIndex; }

    function selectProgramIndex(index as Number) as Void { _programIndex = index; }

    // Commit the highlighted program and remember it across restarts.
    function chooseSelectedProgram() as Void {
        _programId = programIdAt(_programIndex);
        Application.Storage.setValue("lift_program_id", _programId);
        Application.Storage.setValue("lift_program_name", programLabel(_programIndex));
    }

    function chosenProgramId() as String {
        if (_programId == null or _programId.equals("")) { return "current"; }
        return _programId;
    }

    // After choosing a different program, pull its plan in the background.
    function reloadPlan() as Void {
        if (_comms != null) { _comms.fetchPlan(chosenProgramId()); }
    }

    function chosenProgramName() as String {
        var n = Application.Storage.getValue("lift_program_name");
        if (n == null) { return ""; }
        return n as String;
    }

    // ------------------------------------------------------------ backend sync

    // Swap in the plan fetched from the backend. Refused once a workout is
    // under way: replacing the plan mid-session would invalidate the cursor.
    function adoptRemotePlan(days as Array) as Boolean {
        if (_started or days.size() == 0) { return false; }
        var keepDay = _dayIndex;   // do not yank the picker back while choosing
        _days = days;
        _section = "";
        for (var i = 0; i < _days.size(); i++) {
            var sec = (_days[i] as Dictionary)[:section] as String;
            if (_section.equals("")) { _section = sec; }
        }
        var n = dayCount();
        _dayIndex = (keepDay < n) ? keepDay : 0;
        _exIndex = 0;
        _setIndex = 0;
        _resetEditable();
        return true;
    }

    // The body for POST /api/v1/watch/workout: only sets the user actually
    // completed, in the order they were trained.
    function buildWorkoutBody() as Dictionary or Null {
        var sets = [];
        var exs = currentExercises();
        for (var i = 0; i < exs.size(); i++) {
            var name = (exs[i] as Dictionary)[:name] as String;
            var planSets = (exs[i] as Dictionary)[:sets] as Array;
            // Defensive: _weights/_reps are sized by the plan that was active
            // when the workout began. A restored session or a swapped plan can
            // leave them shorter, and indexing blindly crashed the save.
            if (i >= _weights.size() or i >= _reps.size()) { continue; }
            if (planSets.size() > (_weights[i] as Array).size()) { continue; }
            for (var j = 0; j < planSets.size(); j++) {
                if (!isLogged(i, j)) { continue; }
                sets.add({
                    :exercise => name,
                    :weight => _weights[i][j] as Number,
                    :reps => _reps[i][j] as Number,
                    :amrap => (planSets[j] as Dictionary)[:amrap] as Boolean
                });
            }
        }
        if (sets.size() == 0) { return null; }
        return {
            :day => dayName(_dayIndex),
            :section => _section,
            :program => _program,
            :week => 1,
            :day_in_week => _dayIndex + 1,
            :duration_s => elapsedMs() / 1000,
            :sets => sets
        };
    }

    // Compact stash for a workout that could not be uploaded:
    // "day|section|program|duration;Ex|w|r|a;Ex|w|r|a"
    function pendingText() as String or Null {
        var body = buildWorkoutBodyOrPending();
        if (body == null) { return null; }
        var out = (body[:day] as String) + "|" + (body[:section] as String) + "|" +
                  (body[:program] as String) + "|" + (body[:duration_s] as Number);
        var sets = body[:sets] as Array;
        for (var i = 0; i < sets.size(); i++) {
            var s = sets[i] as Dictionary;
            out += ";" + (s[:exercise] as String) + "|" + (s[:weight] as Number) + "|" +
                   (s[:reps] as Number) + "|" + ((s[:amrap] as Boolean) ? "1" : "0");
        }
        return out;
    }

    // Rebuild a stashed workout so it can be posted again.
    function loadPendingText(text as String) as Boolean {
        var i = text.find(";");
        if (i == null) { return false; }
        var head = text.substring(0, i);
        var fields = _split(head, "|");
        if (fields.size() < 4) { return false; }
        var sets = [];
        var rest = text.substring(i + 1, text.length());
        var parts = _split(rest, ";");
        for (var k = 0; k < parts.size(); k++) {
            var f = _split(parts[k] as String, "|");
            if (f.size() < 4) { continue; }
            sets.add({:exercise => f[0], :weight => (f[1] as String).toNumber(),
                      :reps => (f[2] as String).toNumber(),
                      :amrap => (f[3] as String).equals("1")});
        }
        if (sets.size() == 0) { return false; }
        _pendingBody = {
            :day => fields[0], :section => fields[1], :program => fields[2],
            :duration_s => (fields[3] as String).toNumber(),
            :week => 1, :day_in_week => 1, :sets => sets
        };
        _pendingSets = sets.size();
        return true;
    }

    function buildWorkoutBodyOrPending() as Dictionary or Null {
        if (_pendingBody != null) { return _pendingBody; }
        return buildWorkoutBody();
    }

    function pendingSetCount() as Number { return _pendingSets; }

    private function _split(s as String, sep as String) as Array {
        var out = [];
        var start = 0;
        var len = s.length();
        for (var i = 0; i <= len; i++) {
            var atEnd = (i == len);
            if (atEnd or (s.substring(i, i + 1) as String).equals(sep)) {
                out.add(s.substring(start, i));
                start = i + 1;
            }
        }
        return out;
    }

    // ------------------------------------------------------------------ finish

    // Stop recording and let the user keep or discard the activity. Mirrors the
    // behaviour of the old recording path: no silent Garmin Connect litter.
    function finishWorkout() as Void {
        stopRest();
        _awaitingReps = false;
        if (_session != null and !_sessionStopped) {
            _session.stop();
            _sessionStopped = true;
        }
        var menu = new WatchUi.Menu2({ :title => "Finish workout" });
        menu.addItem(new WatchUi.MenuItem("Save & finish", null, "save", null));
        menu.addItem(new WatchUi.MenuItem("Discard workout", null, "discard", null));
        WatchUi.pushView(menu, new WorkoutFinishDelegate(self), WatchUi.SLIDE_UP);
    }

    // Popping the finish menu without choosing keeps the session open, so a
    // stray BACK cannot throw the workout away.
    function finishMenuDismissed() as Void {
        WatchUi.requestUpdate();
    }

    function resolveSave(save as Boolean) as Void {
        if (save) {
            // Hand the finished workout to the backend, which writes it into
            // Liftosaur. Failures are stashed and retried on the next launch.
            if (_comms != null) { _comms.postWorkout(); }
        }
        if (_session != null) {
            if (save) {
                _session.save();
                _activityNote = "saved to Garmin";
                System.println("Workout: SAVED " + _setsDone + "/" + _setsTotal + " sets");
            } else {
                _session.discard();
                _activityNote = "activity discarded";
            }
            _session = null;
        } else if (save) {
            _activityNote = "nothing to save";
        }
        _started = false;
        clearSaved();
    }

    // Reported on the finish screen: the user could not tell whether the
    // activity reached Garmin Connect, so say so plainly.
    function activityNote() as String { return _activityNote; }
    function syncNote() as String { return _syncNote; }
    function setSyncNote(t as String) as Void { _syncNote = t; }
    function lapsAdded() as Number { return _lapsAdded; }

    function elapsedMs() as Number {
        return _started ? (System.getTimer() - _sessionMs) : 0;
    }
}

class WorkoutFinishDelegate extends WatchUi.Menu2InputDelegate {

    private var _c;

    function initialize(c as WorkoutController) {
        Menu2InputDelegate.initialize();
        _c = c;
    }

    function onSelect(item as WatchUi.MenuItem) as Void {
        _c.resolveSave(item.getId().equals("save"));
        WatchUi.popView(WatchUi.SLIDE_DOWN);
    }
}
