"""Send a workout to the backend, and pull the plan into the watch build.

Two jobs, both against the backend rather than Liftosaur directly:

  --post JSON        POST a logged workout to /api/v1/watch/workout, which
                     writes it into Liftosaur. Use to verify sync-back from a
                     shell without the watch.
  (default)          fetch /api/v1/watch/plan and emit source/PlanData.mc, the
                     plan baked into the app as the offline fallback.

The plan is COMPILED BY THE BACKEND (app/plan.py) - this script deliberately has
no parser of its own, so there is exactly one implementation of the weight maths
and the Liftoscript subset. Point --url at the https tunnel, or --from-json at a
saved plan to build with no backend running.
"""
from __future__ import annotations

import argparse
import json
import os
import sys
import urllib.error
import urllib.request

def _default_url() -> str:
    """LIFTOSAUR_BACKEND, else the hostname recorded by liftosaur-tunnel.service.

    NOT a hardcoded hostname: a quick tunnel's is regenerated on every restart,
    and a stale one silently breaks regeneration (and used to be baked into the
    watch too).
    """
    env = os.environ.get("LIFTOSAUR_BACKEND")
    if env:
        return env.rstrip("/")
    try:
        with open(os.path.expanduser("~/.liftosaur-tunnel-url")) as fh:
            return fh.read().strip().rstrip("/")
    except OSError:
        return "http://localhost:8008"


DEFAULT_URL = _default_url()


def http_json(url: str, payload: dict | None = None, timeout: int = 60):
    data = json.dumps(payload).encode() if payload is not None else None
    req = urllib.request.Request(
        url, data=data, method="POST" if data else "GET",
        headers={"Content-Type": "application/json"} if data else {})
    with urllib.request.urlopen(req, timeout=timeout) as resp:
        return json.loads(resp.read().decode())


def emit_mc(plan: dict, section: str) -> str:
    days = [d for d in plan["days"] if not section or d.get("section") == section]
    L = ["// GENERATED by tools/plan_from_liftosaur.py - do not edit by hand.",
         "// Source: %s (compiled by backend/python/app/plan.py)" % plan.get("program", "?"),
         "// Section: %s" % (section or "(all)"),
         "",
         "import Toybox.Lang;",
         "",
         "module LiftPlan {", "",
         "    // The Liftosaur program name. The history write-back MUST carry this",
         "    // exact name: Liftosaur rejects a record whose program does not exist.",
         '    function program() as String {',
         '        return "%s";' % plan.get("program", "").replace('"', "'"),
         "    }", "",
         "    // The whole plan: array of days, each with exercises and resolved sets.",
         "    function days() as Array {",
         "        return ["]
    for d in days:
        L.append('            {:name => "%s", :section => "%s", :exercises => ['
                 % (d["name"], d.get("section", "")))
        for ex in d["exercises"]:
            L.append('                {:name => "%s", :rest => %d, :sets => ['
                     % (ex["name"], ex["rest"]))
            for s in ex["sets"]:
                L.append('                    {:reps => %d, :weight => %d, '
                         ':amrap => %s, :rest => %d},'
                         % (s["reps"], int(s["weight"]),
                            "true" if s["amrap"] else "false", s["rest"]))
            L.append("                ]},")
        L.append("            ]},")
    L += ["        ];", "    }", "}"]
    return "\n".join(L) + "\n"


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--url", default=DEFAULT_URL,
                    help="backend base url (default: %(default)s)")
    ap.add_argument("--from-json", default=None,
                    help="read a saved plan instead of calling the backend")
    ap.add_argument("--section", default="",
                    help="section to bake in ('' = every week-block, which is "
                         "what the watch wants: it offers all days).")
    ap.add_argument("--out-mc", default="source/PlanData.mc")
    ap.add_argument("--post", default=None,
                    help="path to a workout JSON to POST instead of generating")
    args = ap.parse_args()

    if args.post:
        body = json.load(open(args.post))
        try:
            res = http_json(f"{args.url}/api/v1/watch/workout", body)
        except urllib.error.HTTPError as exc:
            print(f"FAILED {exc.code}: {exc.read().decode()[:300]}", file=sys.stderr)
            return 1
        print(json.dumps(res, indent=2)[:1200])
        return 0

    if args.from_json:
        plan = json.load(open(args.from_json))
    else:
        try:
            plan = http_json(f"{args.url}/api/v1/watch/plan")
        except urllib.error.HTTPError as exc:
            print(f"backend returned {exc.code}: "
                  f"{exc.read().decode()[:200]}", file=sys.stderr)
            return 1
        except OSError as exc:
            print(f"cannot reach {args.url}: {exc}\n"
                  f"(use --from-json for an offline build)", file=sys.stderr)
            return 1

    days = [d for d in plan["days"] if not args.section
            or d.get("section") == args.section]
    warns = plan.get("warnings", [])
    print(f"program: {plan.get('program')}")
    print(f"section: {args.section or '(all)'} -> {len(days)} days")
    for d in days:
        tot = sum(len(e["sets"]) for e in d["exercises"])
        print(f"  {d['name']}: {len(d['exercises'])} exercises, {tot} sets")
    if warns:
        print(f"WARNINGS ({len(warns)}):")
        for w in warns[:10]:
            print("  !", w)

    os.makedirs(os.path.dirname(args.out_mc) or ".", exist_ok=True)
    with open(args.out_mc, "w") as fh:
        fh.write(emit_mc(plan, args.section))
    print(f"wrote {args.out_mc}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
